# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../../../ui/integrated_matching.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(587, 419)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setWindowTitle("Integrated Matching")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.Rs_input = QtWidgets.QLineEdit(self.centralwidget)
        self.Rs_input.setObjectName("Rs_input")
        self.gridLayout.addWidget(self.Rs_input, 3, 1, 1, 1)
        self.label_92 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_92.sizePolicy().hasHeightForWidth())
        self.label_92.setSizePolicy(sizePolicy)
        self.label_92.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_92.setObjectName("label_92")
        self.gridLayout.addWidget(self.label_92, 3, 2, 1, 1)
        self.label_91 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_91.sizePolicy().hasHeightForWidth())
        self.label_91.setSizePolicy(sizePolicy)
        self.label_91.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_91.setObjectName("label_91")
        self.gridLayout.addWidget(self.label_91, 3, 0, 1, 1)
        self.label_84 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_84.sizePolicy().hasHeightForWidth())
        self.label_84.setSizePolicy(sizePolicy)
        self.label_84.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_84.setObjectName("label_84")
        self.gridLayout.addWidget(self.label_84, 0, 2, 1, 1)
        self.Vt_input = QtWidgets.QLineEdit(self.centralwidget)
        self.Vt_input.setObjectName("Vt_input")
        self.gridLayout.addWidget(self.Vt_input, 1, 1, 1, 1)
        self.label_82 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_82.sizePolicy().hasHeightForWidth())
        self.label_82.setSizePolicy(sizePolicy)
        self.label_82.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_82.setObjectName("label_82")
        self.gridLayout.addWidget(self.label_82, 0, 0, 1, 1)
        self.label_85 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_85.sizePolicy().hasHeightForWidth())
        self.label_85.setSizePolicy(sizePolicy)
        self.label_85.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_85.setObjectName("label_85")
        self.gridLayout.addWidget(self.label_85, 1, 2, 1, 1)
        self.label_86 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_86.sizePolicy().hasHeightForWidth())
        self.label_86.setSizePolicy(sizePolicy)
        self.label_86.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_86.setObjectName("label_86")
        self.gridLayout.addWidget(self.label_86, 1, 0, 1, 1)
        self.Ic_input = QtWidgets.QLineEdit(self.centralwidget)
        self.Ic_input.setObjectName("Ic_input")
        self.gridLayout.addWidget(self.Ic_input, 0, 1, 1, 1)
        self.ft_input = QtWidgets.QLineEdit(self.centralwidget)
        self.ft_input.setObjectName("ft_input")
        self.gridLayout.addWidget(self.ft_input, 2, 1, 1, 1)
        self.label_87 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_87.sizePolicy().hasHeightForWidth())
        self.label_87.setSizePolicy(sizePolicy)
        self.label_87.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_87.setObjectName("label_87")
        self.gridLayout.addWidget(self.label_87, 2, 0, 1, 1)
        self.label_88 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_88.sizePolicy().hasHeightForWidth())
        self.label_88.setSizePolicy(sizePolicy)
        self.label_88.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_88.setObjectName("label_88")
        self.gridLayout.addWidget(self.label_88, 2, 2, 1, 1)
        self.f0_input = QtWidgets.QLineEdit(self.centralwidget)
        self.f0_input.setObjectName("f0_input")
        self.gridLayout.addWidget(self.f0_input, 4, 1, 5, 1)
        self.label_90 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_90.sizePolicy().hasHeightForWidth())
        self.label_90.setSizePolicy(sizePolicy)
        self.label_90.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_90.setObjectName("label_90")
        self.gridLayout.addWidget(self.label_90, 4, 0, 5, 1)
        self.label_89 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_89.sizePolicy().hasHeightForWidth())
        self.label_89.setSizePolicy(sizePolicy)
        self.label_89.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_89.setObjectName("label_89")
        self.gridLayout.addWidget(self.label_89, 4, 2, 5, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 2, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 0, 1, 1)
        self.Le_text_browser = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Le_text_browser.sizePolicy().hasHeightForWidth())
        self.Le_text_browser.setSizePolicy(sizePolicy)
        self.Le_text_browser.setMaximumSize(QtCore.QSize(16777215, 21))
        self.Le_text_browser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Le_text_browser.setObjectName("Le_text_browser")
        self.gridLayout_3.addWidget(self.Le_text_browser, 0, 2, 1, 1)
        self.label_95 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_95.sizePolicy().hasHeightForWidth())
        self.label_95.setSizePolicy(sizePolicy)
        self.label_95.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_95.setObjectName("label_95")
        self.gridLayout_3.addWidget(self.label_95, 0, 3, 1, 1)
        self.Lb_text_browser = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Lb_text_browser.sizePolicy().hasHeightForWidth())
        self.Lb_text_browser.setSizePolicy(sizePolicy)
        self.Lb_text_browser.setMaximumSize(QtCore.QSize(16777215, 21))
        self.Lb_text_browser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Lb_text_browser.setObjectName("Lb_text_browser")
        self.gridLayout_3.addWidget(self.Lb_text_browser, 1, 2, 1, 1)
        self.label_96 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_96.sizePolicy().hasHeightForWidth())
        self.label_96.setSizePolicy(sizePolicy)
        self.label_96.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_96.setObjectName("label_96")
        self.gridLayout_3.addWidget(self.label_96, 1, 3, 1, 1)
        self.label_78 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_78.sizePolicy().hasHeightForWidth())
        self.label_78.setSizePolicy(sizePolicy)
        self.label_78.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_78.setObjectName("label_78")
        self.gridLayout_3.addWidget(self.label_78, 0, 1, 1, 1)
        self.label_83 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_83.sizePolicy().hasHeightForWidth())
        self.label_83.setSizePolicy(sizePolicy)
        self.label_83.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_83.setObjectName("label_83")
        self.gridLayout_3.addWidget(self.label_83, 1, 1, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.clean_integrated_matching_button = QtWidgets.QPushButton(self.centralwidget)
        self.clean_integrated_matching_button.setObjectName("clean_integrated_matching_button")
        self.gridLayout_4.addWidget(self.clean_integrated_matching_button, 0, 0, 1, 1)
        self.calculate_integrated_matching_button = QtWidgets.QPushButton(self.centralwidget)
        self.calculate_integrated_matching_button.setDefault(True)
        self.calculate_integrated_matching_button.setObjectName("calculate_integrated_matching_button")
        self.gridLayout_4.addWidget(self.calculate_integrated_matching_button, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 3, 2, 1, 1)
        self.Lb_vs_Ic_button = QtWidgets.QPushButton(self.centralwidget)
        self.Lb_vs_Ic_button.setObjectName("Lb_vs_Ic_button")
        self.gridLayout_3.addWidget(self.Lb_vs_Ic_button, 3, 0, 1, 2)
        self.gridLayout_5.addLayout(self.gridLayout_3, 2, 0, 1, 3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem4, 1, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_94 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_94.sizePolicy().hasHeightForWidth())
        self.label_94.setSizePolicy(sizePolicy)
        self.label_94.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_94.setObjectName("label_94")
        self.gridLayout_2.addWidget(self.label_94, 2, 0, 1, 1)
        self.label_98 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_98.sizePolicy().hasHeightForWidth())
        self.label_98.setSizePolicy(sizePolicy)
        self.label_98.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_98.setObjectName("label_98")
        self.gridLayout_2.addWidget(self.label_98, 2, 2, 1, 2)
        self.label_93 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_93.sizePolicy().hasHeightForWidth())
        self.label_93.setSizePolicy(sizePolicy)
        self.label_93.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_93.setObjectName("label_93")
        self.gridLayout_2.addWidget(self.label_93, 1, 0, 1, 1)
        self.gm_text_browser = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gm_text_browser.sizePolicy().hasHeightForWidth())
        self.gm_text_browser.setSizePolicy(sizePolicy)
        self.gm_text_browser.setMaximumSize(QtCore.QSize(16777215, 21))
        self.gm_text_browser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.gm_text_browser.setObjectName("gm_text_browser")
        self.gridLayout_2.addWidget(self.gm_text_browser, 1, 1, 1, 1)
        self.c_pi_text_browser = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c_pi_text_browser.sizePolicy().hasHeightForWidth())
        self.c_pi_text_browser.setSizePolicy(sizePolicy)
        self.c_pi_text_browser.setMaximumSize(QtCore.QSize(16777215, 21))
        self.c_pi_text_browser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.c_pi_text_browser.setObjectName("c_pi_text_browser")
        self.gridLayout_2.addWidget(self.c_pi_text_browser, 2, 1, 1, 1)
        self.label_97 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_97.sizePolicy().hasHeightForWidth())
        self.label_97.setSizePolicy(sizePolicy)
        self.label_97.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_97.setObjectName("label_97")
        self.gridLayout_2.addWidget(self.label_97, 1, 2, 1, 2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 0, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem6, 3, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 0, 2, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 587, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuDocs = QtWidgets.QMenu(self.menuBar)
        self.menuDocs.setObjectName("menuDocs")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actiondsd = QtWidgets.QAction(MainWindow)
        self.actiondsd.setObjectName("actiondsd")
        self.action_Open_formulas = QtWidgets.QAction(MainWindow)
        self.action_Open_formulas.setObjectName("action_Open_formulas")
        self.action_Quit_IM = QtWidgets.QAction(MainWindow)
        self.action_Quit_IM.setObjectName("action_Quit_IM")
        self.menuDocs.addAction(self.action_Open_formulas)
        self.menuFile.addAction(self.action_Quit_IM)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuDocs.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.Ic_input, self.Vt_input)
        MainWindow.setTabOrder(self.Vt_input, self.ft_input)
        MainWindow.setTabOrder(self.ft_input, self.Rs_input)
        MainWindow.setTabOrder(self.Rs_input, self.f0_input)
        MainWindow.setTabOrder(self.f0_input, self.clean_integrated_matching_button)
        MainWindow.setTabOrder(self.clean_integrated_matching_button, self.gm_text_browser)
        MainWindow.setTabOrder(self.gm_text_browser, self.c_pi_text_browser)
        MainWindow.setTabOrder(self.c_pi_text_browser, self.Lb_text_browser)
        MainWindow.setTabOrder(self.Lb_text_browser, self.calculate_integrated_matching_button)
        MainWindow.setTabOrder(self.calculate_integrated_matching_button, self.Le_text_browser)
        MainWindow.setTabOrder(self.Le_text_browser, self.Lb_vs_Ic_button)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.Rs_input.setPlaceholderText(_translate("MainWindow", "50"))
        self.label_92.setText(_translate("MainWindow", "<html><head/><body><p>Ω</p></body></html>"))
        self.label_91.setText(_translate("MainWindow", "<html><head/><body><p>R<span style=\" vertical-align:sub;\">s</span></p></body></html>"))
        self.label_84.setText(_translate("MainWindow", "<html><head/><body><p>mA</p></body></html>"))
        self.Vt_input.setPlaceholderText(_translate("MainWindow", "25"))
        self.label_82.setText(_translate("MainWindow", "<html><head/><body><p>I<span style=\" vertical-align:sub;\">C</span></p></body></html>"))
        self.label_85.setText(_translate("MainWindow", "<html><head/><body><p>mV</p></body></html>"))
        self.label_86.setText(_translate("MainWindow", "<html><head/><body><p>V<span style=\" vertical-align:sub;\">T</span></p></body></html>"))
        self.Ic_input.setPlaceholderText(_translate("MainWindow", "0.24*15"))
        self.ft_input.setPlaceholderText(_translate("MainWindow", "50"))
        self.label_87.setText(_translate("MainWindow", "<html><head/><body><p>f<span style=\" vertical-align:sub;\">T</span></p></body></html>"))
        self.label_88.setText(_translate("MainWindow", "<html><head/><body><p>GHz</p></body></html>"))
        self.f0_input.setPlaceholderText(_translate("MainWindow", "5.25"))
        self.label_90.setText(_translate("MainWindow", "<html><head/><body><p>f<span style=\" vertical-align:sub;\">0</span></p></body></html>"))
        self.label_89.setText(_translate("MainWindow", "<html><head/><body><p>GHz</p></body></html>"))
        self.label_95.setText(_translate("MainWindow", "<html><head/><body><p>pH</p></body></html>"))
        self.label_96.setText(_translate("MainWindow", "<html><head/><body><p>nH</p></body></html>"))
        self.label_78.setText(_translate("MainWindow", "<html><head/><body><p>L<span style=\" vertical-align:sub;\">E</span></p></body></html>"))
        self.label_83.setText(_translate("MainWindow", "<html><head/><body><p>L<span style=\" vertical-align:sub;\">B</span></p></body></html>"))
        self.clean_integrated_matching_button.setText(_translate("MainWindow", "Clean"))
        self.calculate_integrated_matching_button.setText(_translate("MainWindow", "Calculate"))
        self.Lb_vs_Ic_button.setText(_translate("MainWindow", "Plot Lb(Ic)"))
        self.label_94.setText(_translate("MainWindow", "<html><head/><body><p>C<span style=\" vertical-align:sub;\">π</span></p></body></html>"))
        self.label_98.setText(_translate("MainWindow", "<html><head/><body><p>fF</p></body></html>"))
        self.label_93.setText(_translate("MainWindow", "<html><head/><body><p>g<span style=\" vertical-align:sub;\">m</span></p></body></html>"))
        self.label_97.setText(_translate("MainWindow", "<html><head/><body><p>mS</p></body></html>"))
        self.menuDocs.setTitle(_translate("MainWindow", "Docs"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actiondsd.setText(_translate("MainWindow", "dsd"))
        self.action_Open_formulas.setText(_translate("MainWindow", "&Open formulas"))
        self.action_Quit_IM.setText(_translate("MainWindow", "&Quit"))
        self.action_Quit_IM.setShortcut(_translate("MainWindow", "Ctrl+W"))

