# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/parallel_stub_matching.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(617, 691)
        MainWindow.setWindowTitle("Parallel Stub Matching")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ZL_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.ZL_lineedit.setGeometry(QtCore.QRect(110, 50, 131, 21))
        self.ZL_lineedit.setReadOnly(False)
        self.ZL_lineedit.setObjectName("ZL_lineedit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 50, 60, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 60, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 210, 60, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 250, 71, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(580, 90, 21, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(570, 250, 21, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 20, 60, 16))
        self.label_7.setObjectName("label_7")
        self.Z0_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.Z0_lineedit.setGeometry(QtCore.QRect(110, 20, 131, 21))
        self.Z0_lineedit.setReadOnly(False)
        self.Z0_lineedit.setObjectName("Z0_lineedit")
        self.Calculate_button = QtWidgets.QPushButton(self.centralwidget)
        self.Calculate_button.setGeometry(QtCore.QRect(490, 610, 99, 32))
        self.Calculate_button.setAutoDefault(True)
        self.Calculate_button.setDefault(True)
        self.Calculate_button.setObjectName("Calculate_button")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(260, 20, 60, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(260, 50, 60, 16))
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(20, 350, 60, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(390, 350, 60, 16))
        self.label_12.setObjectName("label_12")
        self.Zv1_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.Zv1_lineedit.setGeometry(QtCore.QRect(100, 350, 271, 21))
        self.Zv1_lineedit.setReadOnly(True)
        self.Zv1_lineedit.setObjectName("Zv1_lineedit")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(20, 380, 60, 16))
        self.label_14.setObjectName("label_14")
        self.zv1_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.zv1_lineedit.setGeometry(QtCore.QRect(100, 380, 271, 21))
        self.zv1_lineedit.setReadOnly(True)
        self.zv1_lineedit.setObjectName("zv1_lineedit")
        self.zv2_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.zv2_lineedit.setGeometry(QtCore.QRect(100, 560, 271, 21))
        self.zv2_lineedit.setReadOnly(True)
        self.zv2_lineedit.setObjectName("zv2_lineedit")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(390, 530, 60, 16))
        self.label_13.setObjectName("label_13")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(20, 530, 60, 16))
        self.label_15.setObjectName("label_15")
        self.Zv2_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.Zv2_lineedit.setGeometry(QtCore.QRect(100, 530, 271, 21))
        self.Zv2_lineedit.setReadOnly(True)
        self.Zv2_lineedit.setObjectName("Zv2_lineedit")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(20, 560, 60, 16))
        self.label_16.setObjectName("label_16")
        self.yv1_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.yv1_lineedit.setGeometry(QtCore.QRect(100, 450, 271, 21))
        self.yv1_lineedit.setText("")
        self.yv1_lineedit.setReadOnly(True)
        self.yv1_lineedit.setObjectName("yv1_lineedit")
        self.Yv1_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.Yv1_lineedit.setGeometry(QtCore.QRect(100, 420, 271, 21))
        self.Yv1_lineedit.setText("")
        self.Yv1_lineedit.setReadOnly(True)
        self.Yv1_lineedit.setObjectName("Yv1_lineedit")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(20, 450, 60, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(390, 420, 60, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(20, 420, 60, 16))
        self.label_19.setObjectName("label_19")
        self.distance_horizontalScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.distance_horizontalScrollBar.setGeometry(QtCore.QRect(110, 90, 361, 16))
        self.distance_horizontalScrollBar.setMaximum(500)
        self.distance_horizontalScrollBar.setPageStep(0)
        self.distance_horizontalScrollBar.setProperty("value", 0)
        self.distance_horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.distance_horizontalScrollBar.setObjectName("distance_horizontalScrollBar")
        self.length_horizontalScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.length_horizontalScrollBar.setGeometry(QtCore.QRect(80, 250, 361, 16))
        self.length_horizontalScrollBar.setMaximum(500)
        self.length_horizontalScrollBar.setPageStep(0)
        self.length_horizontalScrollBar.setProperty("value", 250)
        self.length_horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.length_horizontalScrollBar.setObjectName("length_horizontalScrollBar")
        self.Z0_stub_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.Z0_stub_lineedit.setGeometry(QtCore.QRect(90, 180, 131, 21))
        self.Z0_stub_lineedit.setReadOnly(False)
        self.Z0_stub_lineedit.setObjectName("Z0_stub_lineedit")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(240, 180, 60, 16))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(10, 180, 60, 16))
        self.label_21.setObjectName("label_21")
        self.distance_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.distance_lineedit.setGeometry(QtCore.QRect(480, 90, 91, 21))
        self.distance_lineedit.setText("")
        self.distance_lineedit.setReadOnly(True)
        self.distance_lineedit.setObjectName("distance_lineedit")
        self.length_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.length_lineedit.setGeometry(QtCore.QRect(480, 250, 81, 21))
        self.length_lineedit.setReadOnly(True)
        self.length_lineedit.setObjectName("length_lineedit")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(390, 590, 60, 16))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(20, 590, 60, 16))
        self.label_23.setObjectName("label_23")
        self.Yv2_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.Yv2_lineedit.setGeometry(QtCore.QRect(100, 590, 271, 21))
        self.Yv2_lineedit.setText("")
        self.Yv2_lineedit.setReadOnly(True)
        self.Yv2_lineedit.setObjectName("Yv2_lineedit")
        self.yv2_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.yv2_lineedit.setGeometry(QtCore.QRect(100, 620, 271, 21))
        self.yv2_lineedit.setText("")
        self.yv2_lineedit.setReadOnly(True)
        self.yv2_lineedit.setObjectName("yv2_lineedit")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(20, 620, 60, 16))
        self.label_24.setObjectName("label_24")
        self.OC_radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.OC_radioButton.setGeometry(QtCore.QRect(90, 220, 111, 20))
        self.OC_radioButton.setObjectName("OC_radioButton")
        self.SC_radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.SC_radioButton.setGeometry(QtCore.QRect(220, 220, 121, 20))
        self.SC_radioButton.setObjectName("SC_radioButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 617, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actiondsd = QtWidgets.QAction(MainWindow)
        self.actiondsd.setObjectName("actiondsd")
        self.actionImpedance_d = QtWidgets.QAction(MainWindow)
        self.actionImpedance_d.setObjectName("actionImpedance_d")
        self.actionAbout_2 = QtWidgets.QAction(MainWindow)
        self.actionAbout_2.setObjectName("actionAbout_2")
        self.actionGamma2impedance = QtWidgets.QAction(MainWindow)
        self.actionGamma2impedance.setObjectName("actionGamma2impedance")
        self.action_lambda4 = QtWidgets.QAction(MainWindow)
        self.action_lambda4.setObjectName("action_lambda4")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.Z0_lineedit, self.ZL_lineedit)
        MainWindow.setTabOrder(self.ZL_lineedit, self.Zv1_lineedit)
        MainWindow.setTabOrder(self.Zv1_lineedit, self.zv1_lineedit)
        MainWindow.setTabOrder(self.zv1_lineedit, self.Zv2_lineedit)
        MainWindow.setTabOrder(self.Zv2_lineedit, self.zv2_lineedit)
        MainWindow.setTabOrder(self.zv2_lineedit, self.Calculate_button)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("MainWindow", "<html><head/><body><p>Z<span style=\" vertical-align:sub;\">L</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "d"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p>Z<span style=\" vertical-align:sub;\">L</span> stub</p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p>l stub</p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "λ"))
        self.label_6.setText(_translate("MainWindow", "λ"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p>Z<span style=\" vertical-align:sub;\">0</span></p></body></html>"))
        self.Z0_lineedit.setText(_translate("MainWindow", "50"))
        self.Calculate_button.setText(_translate("MainWindow", "Calculate"))
        self.label_8.setText(_translate("MainWindow", "Ω"))
        self.label_9.setText(_translate("MainWindow", "Ω"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p>Z<span style=\" vertical-align:sub;\">v1</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "Ω"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p>z<span style=\" vertical-align:sub;\">v1</span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "Ω"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p>Z<span style=\" vertical-align:sub;\">v2</span></p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p>z<span style=\" vertical-align:sub;\">v2</span></p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p>y<span style=\" vertical-align:sub;\">v1</span></p></body></html>"))
        self.label_18.setText(_translate("MainWindow", "S"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p>Y<span style=\" vertical-align:sub;\">v1</span></p></body></html>"))
        self.Z0_stub_lineedit.setText(_translate("MainWindow", "50"))
        self.label_20.setText(_translate("MainWindow", "Ω"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p>Z<span style=\" vertical-align:sub;\">0</span> stub</p></body></html>"))
        self.length_lineedit.setText(_translate("MainWindow", "0.25"))
        self.label_22.setText(_translate("MainWindow", "S"))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p>Y<span style=\" vertical-align:sub;\">v2</span></p></body></html>"))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p>y<span style=\" vertical-align:sub;\">v2</span></p></body></html>"))
        self.OC_radioButton.setText(_translate("MainWindow", "Open circuit"))
        self.SC_radioButton.setText(_translate("MainWindow", "Short circuit"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actiondsd.setText(_translate("MainWindow", "dsd"))
        self.actionImpedance_d.setText(_translate("MainWindow", "Impedance @ -d"))
        self.actionImpedance_d.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.actionAbout_2.setText(_translate("MainWindow", "About"))
        self.actionGamma2impedance.setText(_translate("MainWindow", "Γ2z"))
        self.actionGamma2impedance.setShortcut(_translate("MainWindow", "Ctrl+G"))
        self.action_lambda4.setText(_translate("MainWindow", "&λ/4"))
        self.action_lambda4.setShortcut(_translate("MainWindow", "Ctrl+L"))
