# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../../../ui/lumped_matching.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(869, 600)
        MainWindow.setWindowTitle("Lumped Parameters Matching")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_2.addWidget(self.label_19)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.L1_box = QtWidgets.QTextBrowser(self.centralwidget)
        self.L1_box.setMaximumSize(QtCore.QSize(16777215, 21))
        self.L1_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.L1_box.setObjectName("L1_box")
        self.gridLayout_2.addWidget(self.L1_box, 1, 6, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 2, 8, 1, 1)
        self.label_83 = QtWidgets.QLabel(self.centralwidget)
        self.label_83.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_83.setObjectName("label_83")
        self.gridLayout_2.addWidget(self.label_83, 2, 5, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 2, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 3, 2, 1, 6)
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 1, 1, 1, 1)
        self.label_116 = QtWidgets.QLabel(self.centralwidget)
        self.label_116.setText("")
        self.label_116.setObjectName("label_116")
        self.gridLayout_2.addWidget(self.label_116, 4, 7, 1, 1)
        self.label_110 = QtWidgets.QLabel(self.centralwidget)
        self.label_110.setObjectName("label_110")
        self.gridLayout_2.addWidget(self.label_110, 1, 3, 1, 1)
        self.X1_box = QtWidgets.QTextBrowser(self.centralwidget)
        self.X1_box.setMaximumSize(QtCore.QSize(8777215, 21))
        self.X1_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.X1_box.setObjectName("X1_box")
        self.gridLayout_2.addWidget(self.X1_box, 1, 2, 1, 1)
        self.B2_box = QtWidgets.QTextBrowser(self.centralwidget)
        self.B2_box.setMaximumSize(QtCore.QSize(8777215, 21))
        self.B2_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.B2_box.setObjectName("B2_box")
        self.gridLayout_2.addWidget(self.B2_box, 5, 2, 1, 1)
        self.C2_box = QtWidgets.QTextBrowser(self.centralwidget)
        self.C2_box.setMaximumSize(QtCore.QSize(16777215, 21))
        self.C2_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.C2_box.setObjectName("C2_box")
        self.gridLayout_2.addWidget(self.C2_box, 5, 6, 1, 1)
        self.label_117 = QtWidgets.QLabel(self.centralwidget)
        self.label_117.setText("")
        self.label_117.setObjectName("label_117")
        self.gridLayout_2.addWidget(self.label_117, 5, 7, 1, 1)
        self.label_87 = QtWidgets.QLabel(self.centralwidget)
        self.label_87.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_87.setObjectName("label_87")
        self.gridLayout_2.addWidget(self.label_87, 5, 5, 1, 1)
        self.C1_box = QtWidgets.QTextBrowser(self.centralwidget)
        self.C1_box.setMaximumSize(QtCore.QSize(16777215, 21))
        self.C1_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.C1_box.setObjectName("C1_box")
        self.gridLayout_2.addWidget(self.C1_box, 2, 6, 1, 1)
        self.X2_box = QtWidgets.QTextBrowser(self.centralwidget)
        self.X2_box.setMaximumSize(QtCore.QSize(8777215, 21))
        self.X2_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.X2_box.setObjectName("X2_box")
        self.gridLayout_2.addWidget(self.X2_box, 4, 2, 1, 1)
        self.label_74 = QtWidgets.QLabel(self.centralwidget)
        self.label_74.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_74.setObjectName("label_74")
        self.gridLayout_2.addWidget(self.label_74, 5, 1, 1, 1)
        self.B1_box = QtWidgets.QTextBrowser(self.centralwidget)
        self.B1_box.setMaximumSize(QtCore.QSize(8777215, 21))
        self.B1_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.B1_box.setObjectName("B1_box")
        self.gridLayout_2.addWidget(self.B1_box, 2, 2, 1, 1)
        self.label_88 = QtWidgets.QLabel(self.centralwidget)
        self.label_88.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_88.setObjectName("label_88")
        self.gridLayout_2.addWidget(self.label_88, 4, 5, 1, 1)
        self.label_111 = QtWidgets.QLabel(self.centralwidget)
        self.label_111.setObjectName("label_111")
        self.gridLayout_2.addWidget(self.label_111, 2, 3, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 21))
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 0, 2, 1, 1)
        self.label_112 = QtWidgets.QLabel(self.centralwidget)
        self.label_112.setText("")
        self.label_112.setObjectName("label_112")
        self.gridLayout_2.addWidget(self.label_112, 1, 7, 1, 1)
        self.label_115 = QtWidgets.QLabel(self.centralwidget)
        self.label_115.setObjectName("label_115")
        self.gridLayout_2.addWidget(self.label_115, 5, 3, 1, 1)
        self.label_113 = QtWidgets.QLabel(self.centralwidget)
        self.label_113.setText("")
        self.label_113.setObjectName("label_113")
        self.gridLayout_2.addWidget(self.label_113, 2, 7, 1, 1)
        self.label_84 = QtWidgets.QLabel(self.centralwidget)
        self.label_84.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_84.setObjectName("label_84")
        self.gridLayout_2.addWidget(self.label_84, 1, 5, 1, 1)
        self.label_114 = QtWidgets.QLabel(self.centralwidget)
        self.label_114.setObjectName("label_114")
        self.gridLayout_2.addWidget(self.label_114, 4, 3, 1, 1)
        self.label_80 = QtWidgets.QLabel(self.centralwidget)
        self.label_80.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_80.setObjectName("label_80")
        self.gridLayout_2.addWidget(self.label_80, 4, 1, 1, 1)
        self.L2_box = QtWidgets.QTextBrowser(self.centralwidget)
        self.L2_box.setMaximumSize(QtCore.QSize(16777215, 21))
        self.L2_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.L2_box.setObjectName("L2_box")
        self.gridLayout_2.addWidget(self.L2_box, 4, 6, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 2, 4, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 6, 5, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 2, 0, 1, 2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_8.addWidget(self.comboBox, 0, 2, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_8.addWidget(self.comboBox_2, 1, 2, 1, 1)
        self.output_box = QtWidgets.QLineEdit(self.groupBox_2)
        self.output_box.setObjectName("output_box")
        self.gridLayout_8.addWidget(self.output_box, 1, 1, 1, 1)
        self.label_73 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_73.sizePolicy().hasHeightForWidth())
        self.label_73.setSizePolicy(sizePolicy)
        self.label_73.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_73.setObjectName("label_73")
        self.gridLayout_8.addWidget(self.label_73, 1, 0, 1, 1)
        self.input_box = QtWidgets.QLineEdit(self.groupBox_2)
        self.input_box.setObjectName("input_box")
        self.gridLayout_8.addWidget(self.input_box, 0, 1, 1, 1)
        self.label_72 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_72.sizePolicy().hasHeightForWidth())
        self.label_72.setSizePolicy(sizePolicy)
        self.label_72.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_72.setObjectName("label_72")
        self.gridLayout_8.addWidget(self.label_72, 0, 0, 1, 1)
        self.f0_box = QtWidgets.QLineEdit(self.groupBox_2)
        self.f0_box.setObjectName("f0_box")
        self.gridLayout_8.addWidget(self.f0_box, 2, 1, 1, 1)
        self.label_70 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_70.sizePolicy().hasHeightForWidth())
        self.label_70.setSizePolicy(sizePolicy)
        self.label_70.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_70.setObjectName("label_70")
        self.gridLayout_8.addWidget(self.label_70, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_8.addWidget(self.label_7, 2, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_8)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.gridLayout_5.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.adm_output_box = QtWidgets.QTextBrowser(self.groupBox_3)
        self.adm_output_box.setMaximumSize(QtCore.QSize(16777215, 21))
        self.adm_output_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.adm_output_box.setObjectName("adm_output_box")
        self.gridLayout_15.addWidget(self.adm_output_box, 4, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.groupBox_3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_15.addWidget(self.line, 2, 0, 1, 3)
        self.label_109 = QtWidgets.QLabel(self.groupBox_3)
        self.label_109.setObjectName("label_109")
        self.gridLayout_15.addWidget(self.label_109, 4, 2, 1, 1)
        self.imp_output_box = QtWidgets.QTextBrowser(self.groupBox_3)
        self.imp_output_box.setMaximumSize(QtCore.QSize(16777215, 21))
        self.imp_output_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.imp_output_box.setObjectName("imp_output_box")
        self.gridLayout_15.addWidget(self.imp_output_box, 3, 1, 1, 1)
        self.label_107 = QtWidgets.QLabel(self.groupBox_3)
        self.label_107.setObjectName("label_107")
        self.gridLayout_15.addWidget(self.label_107, 1, 2, 1, 1)
        self.imp_input_box = QtWidgets.QTextBrowser(self.groupBox_3)
        self.imp_input_box.setMaximumSize(QtCore.QSize(16777215, 21))
        self.imp_input_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.imp_input_box.setObjectName("imp_input_box")
        self.gridLayout_15.addWidget(self.imp_input_box, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_15.addWidget(self.label_15, 1, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_15.addWidget(self.label_17, 4, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_15.addWidget(self.label_14, 0, 0, 1, 1)
        self.adm_input_box = QtWidgets.QTextBrowser(self.groupBox_3)
        self.adm_input_box.setMaximumSize(QtCore.QSize(16777215, 21))
        self.adm_input_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.adm_input_box.setObjectName("adm_input_box")
        self.gridLayout_15.addWidget(self.adm_input_box, 1, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_15.addWidget(self.label_16, 3, 0, 1, 1)
        self.label_108 = QtWidgets.QLabel(self.groupBox_3)
        self.label_108.setObjectName("label_108")
        self.gridLayout_15.addWidget(self.label_108, 3, 2, 1, 1)
        self.label_106 = QtWidgets.QLabel(self.groupBox_3)
        self.label_106.setObjectName("label_106")
        self.gridLayout_15.addWidget(self.label_106, 0, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem6, 5, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_15)
        self.gridLayout_5.addWidget(self.groupBox_3, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.open_pdf_sketch_button = QtWidgets.QPushButton(self.centralwidget)
        self.open_pdf_sketch_button.setObjectName("open_pdf_sketch_button")
        self.horizontalLayout_2.addWidget(self.open_pdf_sketch_button)
        self.plot = QtWidgets.QPushButton(self.centralwidget)
        self.plot.setAutoDefault(True)
        self.plot.setDefault(False)
        self.plot.setFlat(False)
        self.plot.setObjectName("plot")
        self.horizontalLayout_2.addWidget(self.plot)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.Clean_all_button_3 = QtWidgets.QPushButton(self.centralwidget)
        self.Clean_all_button_3.setObjectName("Clean_all_button_3")
        self.horizontalLayout_2.addWidget(self.Clean_all_button_3)
        self.Calculate_button_3 = QtWidgets.QPushButton(self.centralwidget)
        self.Calculate_button_3.setAutoDefault(True)
        self.Calculate_button_3.setDefault(True)
        self.Calculate_button_3.setObjectName("Calculate_button_3")
        self.horizontalLayout_2.addWidget(self.Calculate_button_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actiondsd = QtWidgets.QAction(MainWindow)
        self.actiondsd.setObjectName("actiondsd")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.input_box, self.output_box)
        MainWindow.setTabOrder(self.output_box, self.f0_box)
        MainWindow.setTabOrder(self.f0_box, self.Clean_all_button_3)
        MainWindow.setTabOrder(self.Clean_all_button_3, self.Calculate_button_3)
        MainWindow.setTabOrder(self.Calculate_button_3, self.L2_box)
        MainWindow.setTabOrder(self.L2_box, self.comboBox_2)
        MainWindow.setTabOrder(self.comboBox_2, self.comboBox)
        MainWindow.setTabOrder(self.comboBox, self.X2_box)
        MainWindow.setTabOrder(self.X2_box, self.B1_box)
        MainWindow.setTabOrder(self.B1_box, self.C1_box)
        MainWindow.setTabOrder(self.C1_box, self.plot)
        MainWindow.setTabOrder(self.plot, self.imp_output_box)
        MainWindow.setTabOrder(self.imp_output_box, self.adm_output_box)
        MainWindow.setTabOrder(self.adm_output_box, self.open_pdf_sketch_button)
        MainWindow.setTabOrder(self.open_pdf_sketch_button, self.adm_input_box)
        MainWindow.setTabOrder(self.adm_input_box, self.imp_input_box)
        MainWindow.setTabOrder(self.imp_input_box, self.C2_box)
        MainWindow.setTabOrder(self.C2_box, self.X1_box)
        MainWindow.setTabOrder(self.X1_box, self.L1_box)
        MainWindow.setTabOrder(self.L1_box, self.B2_box)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt;\">L-section Matching Network</span></p></body></html>"))
        self.label_83.setText(_translate("MainWindow", "C<sub>1</sub>"))
        self.label_24.setText(_translate("MainWindow", "B<sub>1</sub>"))
        self.label_23.setText(_translate("MainWindow", "X<sub>1</sub>"))
        self.label_110.setText(_translate("MainWindow", "Ω"))
        self.label_87.setText(_translate("MainWindow", "C<sub>2</sub>"))
        self.label_74.setText(_translate("MainWindow", "B<sub>2</sub>"))
        self.label_88.setText(_translate("MainWindow", "L<sub>2</sub>"))
        self.label_111.setText(_translate("MainWindow", "mS"))
        self.label_115.setText(_translate("MainWindow", "mS"))
        self.label_84.setText(_translate("MainWindow", "L<sub>1</sub>"))
        self.label_114.setText(_translate("MainWindow", "Ω"))
        self.label_80.setText(_translate("MainWindow", "X<sub>2</sub>"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Impedance [Ω]"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Admittance [mS]"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Impedance [Ω]"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Admittance [mS]"))
        self.label_73.setText(_translate("MainWindow", "Output (Z<sub>0</sub>)"))
        self.label_72.setText(_translate("MainWindow", "Input (Z<sub>L</sub>)"))
        self.label_70.setText(_translate("MainWindow", "f<sub>0</sub>"))
        self.label_7.setText(_translate("MainWindow", "MHz"))
        self.label_109.setText(_translate("MainWindow", "mS"))
        self.label_107.setText(_translate("MainWindow", "mS"))
        self.label_15.setText(_translate("MainWindow", "Input admittance (Y<sub>L</sub>)"))
        self.label_17.setText(_translate("MainWindow", "Output admittance (Y<sub>0</sub>)"))
        self.label_14.setText(_translate("MainWindow", "Input impedance (Z<sub>L</sub>)"))
        self.label_16.setText(_translate("MainWindow", "Output impedance (Z<sub>0</sub>)"))
        self.label_108.setText(_translate("MainWindow", "Ω"))
        self.label_106.setText(_translate("MainWindow", "Ω"))
        self.open_pdf_sketch_button.setText(_translate("MainWindow", "Open schematic"))
        self.plot.setText(_translate("MainWindow", "Show Γ Plot"))
        self.Clean_all_button_3.setText(_translate("MainWindow", "Clean All"))
        self.Calculate_button_3.setText(_translate("MainWindow", "Calculate"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actiondsd.setText(_translate("MainWindow", "dsd"))

