# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../../../ui/matching.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1132, 691)
        MainWindow.setWindowTitle("Matching Network")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.tab_4)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 1060, 583))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_2.addWidget(self.label_19)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.L1_box = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_3)
        self.L1_box.setMaximumSize(QtCore.QSize(16777215, 21))
        self.L1_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.L1_box.setObjectName("L1_box")
        self.gridLayout_2.addWidget(self.L1_box, 1, 6, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 2, 8, 1, 1)
        self.label_83 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_83.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_83.setObjectName("label_83")
        self.gridLayout_2.addWidget(self.label_83, 2, 5, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 2, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 3, 2, 1, 6)
        self.label_23 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 1, 1, 1, 1)
        self.label_116 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_116.setText("")
        self.label_116.setObjectName("label_116")
        self.gridLayout_2.addWidget(self.label_116, 4, 7, 1, 1)
        self.label_110 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_110.setObjectName("label_110")
        self.gridLayout_2.addWidget(self.label_110, 1, 3, 1, 1)
        self.X1_box = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_3)
        self.X1_box.setMaximumSize(QtCore.QSize(8777215, 21))
        self.X1_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.X1_box.setObjectName("X1_box")
        self.gridLayout_2.addWidget(self.X1_box, 1, 2, 1, 1)
        self.B2_box = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_3)
        self.B2_box.setMaximumSize(QtCore.QSize(8777215, 21))
        self.B2_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.B2_box.setObjectName("B2_box")
        self.gridLayout_2.addWidget(self.B2_box, 5, 2, 1, 1)
        self.C2_box = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_3)
        self.C2_box.setMaximumSize(QtCore.QSize(16777215, 21))
        self.C2_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.C2_box.setObjectName("C2_box")
        self.gridLayout_2.addWidget(self.C2_box, 5, 6, 1, 1)
        self.label_117 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_117.setText("")
        self.label_117.setObjectName("label_117")
        self.gridLayout_2.addWidget(self.label_117, 5, 7, 1, 1)
        self.label_87 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_87.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_87.setObjectName("label_87")
        self.gridLayout_2.addWidget(self.label_87, 5, 5, 1, 1)
        self.C1_box = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_3)
        self.C1_box.setMaximumSize(QtCore.QSize(16777215, 21))
        self.C1_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.C1_box.setObjectName("C1_box")
        self.gridLayout_2.addWidget(self.C1_box, 2, 6, 1, 1)
        self.X2_box = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_3)
        self.X2_box.setMaximumSize(QtCore.QSize(8777215, 21))
        self.X2_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.X2_box.setObjectName("X2_box")
        self.gridLayout_2.addWidget(self.X2_box, 4, 2, 1, 1)
        self.label_74 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_74.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_74.setObjectName("label_74")
        self.gridLayout_2.addWidget(self.label_74, 5, 1, 1, 1)
        self.B1_box = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_3)
        self.B1_box.setMaximumSize(QtCore.QSize(8777215, 21))
        self.B1_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.B1_box.setObjectName("B1_box")
        self.gridLayout_2.addWidget(self.B1_box, 2, 2, 1, 1)
        self.label_88 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_88.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_88.setObjectName("label_88")
        self.gridLayout_2.addWidget(self.label_88, 4, 5, 1, 1)
        self.label_111 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_111.setObjectName("label_111")
        self.gridLayout_2.addWidget(self.label_111, 2, 3, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 21))
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 0, 2, 1, 1)
        self.label_112 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_112.setText("")
        self.label_112.setObjectName("label_112")
        self.gridLayout_2.addWidget(self.label_112, 1, 7, 1, 1)
        self.label_115 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_115.setObjectName("label_115")
        self.gridLayout_2.addWidget(self.label_115, 5, 3, 1, 1)
        self.label_113 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_113.setText("")
        self.label_113.setObjectName("label_113")
        self.gridLayout_2.addWidget(self.label_113, 2, 7, 1, 1)
        self.label_84 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_84.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_84.setObjectName("label_84")
        self.gridLayout_2.addWidget(self.label_84, 1, 5, 1, 1)
        self.label_114 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_114.setObjectName("label_114")
        self.gridLayout_2.addWidget(self.label_114, 4, 3, 1, 1)
        self.label_80 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_80.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_80.setObjectName("label_80")
        self.gridLayout_2.addWidget(self.label_80, 4, 1, 1, 1)
        self.L2_box = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_3)
        self.L2_box.setMaximumSize(QtCore.QSize(16777215, 21))
        self.L2_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.L2_box.setObjectName("L2_box")
        self.gridLayout_2.addWidget(self.L2_box, 4, 6, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 2, 4, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 6, 5, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 2, 0, 1, 2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem5, 1, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_8.addWidget(self.comboBox, 0, 2, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_8.addWidget(self.comboBox_2, 1, 2, 1, 1)
        self.output_box = QtWidgets.QLineEdit(self.groupBox_2)
        self.output_box.setObjectName("output_box")
        self.gridLayout_8.addWidget(self.output_box, 1, 1, 1, 1)
        self.label_73 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_73.sizePolicy().hasHeightForWidth())
        self.label_73.setSizePolicy(sizePolicy)
        self.label_73.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_73.setObjectName("label_73")
        self.gridLayout_8.addWidget(self.label_73, 1, 0, 1, 1)
        self.input_box = QtWidgets.QLineEdit(self.groupBox_2)
        self.input_box.setObjectName("input_box")
        self.gridLayout_8.addWidget(self.input_box, 0, 1, 1, 1)
        self.label_72 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_72.sizePolicy().hasHeightForWidth())
        self.label_72.setSizePolicy(sizePolicy)
        self.label_72.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_72.setObjectName("label_72")
        self.gridLayout_8.addWidget(self.label_72, 0, 0, 1, 1)
        self.f0_box = QtWidgets.QLineEdit(self.groupBox_2)
        self.f0_box.setObjectName("f0_box")
        self.gridLayout_8.addWidget(self.f0_box, 2, 1, 1, 1)
        self.label_70 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_70.sizePolicy().hasHeightForWidth())
        self.label_70.setSizePolicy(sizePolicy)
        self.label_70.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_70.setObjectName("label_70")
        self.gridLayout_8.addWidget(self.label_70, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_8.addWidget(self.label_7, 2, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_8)
        self.gridLayout_5.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_15.addWidget(self.label_15, 1, 0, 1, 1)
        self.label_106 = QtWidgets.QLabel(self.groupBox_3)
        self.label_106.setObjectName("label_106")
        self.gridLayout_15.addWidget(self.label_106, 0, 2, 1, 1)
        self.imp_input_box = QtWidgets.QTextBrowser(self.groupBox_3)
        self.imp_input_box.setMaximumSize(QtCore.QSize(16777215, 21))
        self.imp_input_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.imp_input_box.setObjectName("imp_input_box")
        self.gridLayout_15.addWidget(self.imp_input_box, 0, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_15.addWidget(self.label_14, 0, 0, 1, 1)
        self.adm_input_box = QtWidgets.QTextBrowser(self.groupBox_3)
        self.adm_input_box.setMaximumSize(QtCore.QSize(16777215, 21))
        self.adm_input_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.adm_input_box.setObjectName("adm_input_box")
        self.gridLayout_15.addWidget(self.adm_input_box, 1, 1, 1, 1)
        self.label_107 = QtWidgets.QLabel(self.groupBox_3)
        self.label_107.setObjectName("label_107")
        self.gridLayout_15.addWidget(self.label_107, 1, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_15.addWidget(self.label_16, 3, 0, 1, 1)
        self.imp_output_box = QtWidgets.QTextBrowser(self.groupBox_3)
        self.imp_output_box.setMaximumSize(QtCore.QSize(16777215, 21))
        self.imp_output_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.imp_output_box.setObjectName("imp_output_box")
        self.gridLayout_15.addWidget(self.imp_output_box, 3, 1, 1, 1)
        self.label_108 = QtWidgets.QLabel(self.groupBox_3)
        self.label_108.setObjectName("label_108")
        self.gridLayout_15.addWidget(self.label_108, 3, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_15.addWidget(self.label_17, 4, 0, 1, 1)
        self.adm_output_box = QtWidgets.QTextBrowser(self.groupBox_3)
        self.adm_output_box.setMaximumSize(QtCore.QSize(16777215, 21))
        self.adm_output_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.adm_output_box.setObjectName("adm_output_box")
        self.gridLayout_15.addWidget(self.adm_output_box, 4, 1, 1, 1)
        self.label_109 = QtWidgets.QLabel(self.groupBox_3)
        self.label_109.setObjectName("label_109")
        self.gridLayout_15.addWidget(self.label_109, 4, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.groupBox_3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_15.addWidget(self.line, 2, 0, 1, 3)
        self.verticalLayout_5.addLayout(self.gridLayout_15)
        self.gridLayout_5.addWidget(self.groupBox_3, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.open_pdf_sketch_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.open_pdf_sketch_button.setObjectName("open_pdf_sketch_button")
        self.horizontalLayout_2.addWidget(self.open_pdf_sketch_button)
        self.plot = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.plot.setAutoDefault(True)
        self.plot.setDefault(False)
        self.plot.setFlat(False)
        self.plot.setObjectName("plot")
        self.horizontalLayout_2.addWidget(self.plot)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.Clean_all_button_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.Clean_all_button_3.setObjectName("Clean_all_button_3")
        self.horizontalLayout_2.addWidget(self.Clean_all_button_3)
        self.Calculate_button_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.Calculate_button_3.setAutoDefault(True)
        self.Calculate_button_3.setDefault(True)
        self.Calculate_button_3.setObjectName("Calculate_button_3")
        self.horizontalLayout_2.addWidget(self.Calculate_button_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_12.addLayout(self.verticalLayout_2)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_8.addWidget(self.scrollArea_3)
        self.tabWidget_3.addTab(self.tab_4, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.tab_7)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_7)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem8)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_222 = QtWidgets.QLabel(self.groupBox_4)
        self.label_222.setObjectName("label_222")
        self.gridLayout.addWidget(self.label_222, 10, 4, 1, 1)
        self.w_over_h_box = QtWidgets.QLineEdit(self.groupBox_4)
        self.w_over_h_box.setEnabled(True)
        self.w_over_h_box.setAutoFillBackground(False)
        self.w_over_h_box.setReadOnly(True)
        self.w_over_h_box.setPlaceholderText("")
        self.w_over_h_box.setObjectName("w_over_h_box")
        self.gridLayout.addWidget(self.w_over_h_box, 6, 3, 1, 1)
        self.w_box = QtWidgets.QLineEdit(self.groupBox_4)
        self.w_box.setEnabled(True)
        self.w_box.setReadOnly(False)
        self.w_box.setPlaceholderText("")
        self.w_box.setObjectName("w_box")
        self.gridLayout.addWidget(self.w_box, 3, 3, 1, 1)
        self.label_224 = QtWidgets.QLabel(self.groupBox_4)
        self.label_224.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_224.setObjectName("label_224")
        self.gridLayout.addWidget(self.label_224, 7, 1, 1, 2)
        self.lambda_over_lambda_tem_box = QtWidgets.QLineEdit(self.groupBox_4)
        self.lambda_over_lambda_tem_box.setEnabled(True)
        self.lambda_over_lambda_tem_box.setReadOnly(True)
        self.lambda_over_lambda_tem_box.setPlaceholderText("")
        self.lambda_over_lambda_tem_box.setObjectName("lambda_over_lambda_tem_box")
        self.gridLayout.addWidget(self.lambda_over_lambda_tem_box, 7, 3, 1, 1)
        self.label_212 = QtWidgets.QLabel(self.groupBox_4)
        self.label_212.setObjectName("label_212")
        self.gridLayout.addWidget(self.label_212, 3, 4, 1, 1)
        self.label_207 = QtWidgets.QLabel(self.groupBox_4)
        self.label_207.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_207.setObjectName("label_207")
        self.gridLayout.addWidget(self.label_207, 8, 1, 1, 2)
        self.lambda_tem_box = QtWidgets.QLineEdit(self.groupBox_4)
        self.lambda_tem_box.setEnabled(True)
        self.lambda_tem_box.setReadOnly(True)
        self.lambda_tem_box.setPlaceholderText("")
        self.lambda_tem_box.setObjectName("lambda_tem_box")
        self.gridLayout.addWidget(self.lambda_tem_box, 8, 3, 1, 1)
        self.length_box = QtWidgets.QLineEdit(self.groupBox_4)
        self.length_box.setEnabled(True)
        self.length_box.setReadOnly(True)
        self.length_box.setPlaceholderText("")
        self.length_box.setObjectName("length_box")
        self.gridLayout.addWidget(self.length_box, 10, 3, 1, 1)
        self.label_206 = QtWidgets.QLabel(self.groupBox_4)
        self.label_206.setObjectName("label_206")
        self.gridLayout.addWidget(self.label_206, 5, 4, 1, 1)
        self.f_box_3 = QtWidgets.QLineEdit(self.groupBox_4)
        self.f_box_3.setPlaceholderText("")
        self.f_box_3.setObjectName("f_box_3")
        self.gridLayout.addWidget(self.f_box_3, 5, 3, 1, 1)
        self.label_202 = QtWidgets.QLabel(self.groupBox_4)
        self.label_202.setObjectName("label_202")
        self.gridLayout.addWidget(self.label_202, 4, 4, 1, 1)
        self.h_box = QtWidgets.QLineEdit(self.groupBox_4)
        self.h_box.setPlaceholderText("")
        self.h_box.setObjectName("h_box")
        self.gridLayout.addWidget(self.h_box, 4, 3, 1, 1)
        self.z0box = QtWidgets.QLineEdit(self.groupBox_4)
        self.z0box.setEnabled(True)
        self.z0box.setObjectName("z0box")
        self.gridLayout.addWidget(self.z0box, 1, 3, 1, 1)
        self.epsilon_r_box = QtWidgets.QLineEdit(self.groupBox_4)
        self.epsilon_r_box.setEnabled(True)
        self.epsilon_r_box.setObjectName("epsilon_r_box")
        self.gridLayout.addWidget(self.epsilon_r_box, 2, 3, 1, 1)
        self.label_223 = QtWidgets.QLabel(self.groupBox_4)
        self.label_223.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_223.setObjectName("label_223")
        self.gridLayout.addWidget(self.label_223, 10, 1, 1, 2)
        self.label_218 = QtWidgets.QLabel(self.groupBox_4)
        self.label_218.setObjectName("label_218")
        self.gridLayout.addWidget(self.label_218, 9, 4, 1, 1)
        self.lambda_box = QtWidgets.QLineEdit(self.groupBox_4)
        self.lambda_box.setEnabled(True)
        self.lambda_box.setReadOnly(True)
        self.lambda_box.setPlaceholderText("")
        self.lambda_box.setObjectName("lambda_box")
        self.gridLayout.addWidget(self.lambda_box, 9, 3, 1, 1)
        self.label_216 = QtWidgets.QLabel(self.groupBox_4)
        self.label_216.setObjectName("label_216")
        self.gridLayout.addWidget(self.label_216, 8, 4, 1, 1)
        self.label_204 = QtWidgets.QLabel(self.groupBox_4)
        self.label_204.setObjectName("label_204")
        self.gridLayout.addWidget(self.label_204, 1, 4, 1, 1)
        self.l_lambda_box = QtWidgets.QLineEdit(self.groupBox_4)
        self.l_lambda_box.setPlaceholderText("")
        self.l_lambda_box.setObjectName("l_lambda_box")
        self.gridLayout.addWidget(self.l_lambda_box, 0, 3, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 5, 0, 1, 1)
        self.label_210 = QtWidgets.QLabel(self.groupBox_4)
        self.label_210.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_210.setObjectName("label_210")
        self.gridLayout.addWidget(self.label_210, 6, 1, 1, 2)
        self.label_199 = QtWidgets.QLabel(self.groupBox_4)
        self.label_199.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_199.setObjectName("label_199")
        self.gridLayout.addWidget(self.label_199, 5, 1, 1, 2)
        self.label_198 = QtWidgets.QLabel(self.groupBox_4)
        self.label_198.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_198.setObjectName("label_198")
        self.gridLayout.addWidget(self.label_198, 4, 1, 1, 2)
        self.label_215 = QtWidgets.QLabel(self.groupBox_4)
        self.label_215.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_215.setObjectName("label_215")
        self.gridLayout.addWidget(self.label_215, 3, 1, 1, 2)
        self.label_191 = QtWidgets.QLabel(self.groupBox_4)
        self.label_191.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_191.setObjectName("label_191")
        self.gridLayout.addWidget(self.label_191, 2, 1, 1, 2)
        self.label_203 = QtWidgets.QLabel(self.groupBox_4)
        self.label_203.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_203.setObjectName("label_203")
        self.gridLayout.addWidget(self.label_203, 1, 1, 1, 2)
        self.label_209 = QtWidgets.QLabel(self.groupBox_4)
        self.label_209.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_209.setObjectName("label_209")
        self.gridLayout.addWidget(self.label_209, 0, 1, 1, 2)
        self.label_220 = QtWidgets.QLabel(self.groupBox_4)
        self.label_220.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_220.setObjectName("label_220")
        self.gridLayout.addWidget(self.label_220, 9, 1, 1, 2)
        self.verticalLayout_14.addLayout(self.gridLayout)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem10)
        self.verticalLayout_30.addLayout(self.verticalLayout_14)
        self.horizontalLayout_4.addWidget(self.groupBox_4)
        spacerItem11 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_242 = QtWidgets.QLabel(self.groupBox_5)
        self.label_242.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_242.setObjectName("label_242")
        self.gridLayout_3.addWidget(self.label_242, 10, 0, 1, 1)
        self.label_225 = QtWidgets.QLabel(self.groupBox_5)
        self.label_225.setObjectName("label_225")
        self.gridLayout_3.addWidget(self.label_225, 1, 2, 1, 1)
        self.h_box_2 = QtWidgets.QLineEdit(self.groupBox_5)
        self.h_box_2.setPlaceholderText("")
        self.h_box_2.setObjectName("h_box_2")
        self.gridLayout_3.addWidget(self.h_box_2, 3, 1, 1, 1)
        self.f_box_4 = QtWidgets.QLineEdit(self.groupBox_5)
        self.f_box_4.setPlaceholderText("")
        self.f_box_4.setObjectName("f_box_4")
        self.gridLayout_3.addWidget(self.f_box_4, 7, 1, 1, 1)
        self.lambda_tem_box_2 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lambda_tem_box_2.setEnabled(True)
        self.lambda_tem_box_2.setReadOnly(True)
        self.lambda_tem_box_2.setPlaceholderText("")
        self.lambda_tem_box_2.setObjectName("lambda_tem_box_2")
        self.gridLayout_3.addWidget(self.lambda_tem_box_2, 9, 1, 1, 1)
        self.label_240 = QtWidgets.QLabel(self.groupBox_5)
        self.label_240.setObjectName("label_240")
        self.gridLayout_3.addWidget(self.label_240, 2, 2, 1, 1)
        self.label_237 = QtWidgets.QLabel(self.groupBox_5)
        self.label_237.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_237.setObjectName("label_237")
        self.gridLayout_3.addWidget(self.label_237, 1, 0, 1, 1)
        self.label_235 = QtWidgets.QLabel(self.groupBox_5)
        self.label_235.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_235.setObjectName("label_235")
        self.gridLayout_3.addWidget(self.label_235, 4, 0, 1, 1)
        self.label_227 = QtWidgets.QLabel(self.groupBox_5)
        self.label_227.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_227.setObjectName("label_227")
        self.gridLayout_3.addWidget(self.label_227, 11, 0, 1, 1)
        self.l_lambda_box_2 = QtWidgets.QLineEdit(self.groupBox_5)
        self.l_lambda_box_2.setReadOnly(True)
        self.l_lambda_box_2.setPlaceholderText("")
        self.l_lambda_box_2.setObjectName("l_lambda_box_2")
        self.gridLayout_3.addWidget(self.l_lambda_box_2, 11, 1, 1, 1)
        self.label_234 = QtWidgets.QLabel(self.groupBox_5)
        self.label_234.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_234.setObjectName("label_234")
        self.gridLayout_3.addWidget(self.label_234, 7, 0, 1, 1)
        self.label_230 = QtWidgets.QLabel(self.groupBox_5)
        self.label_230.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_230.setObjectName("label_230")
        self.gridLayout_3.addWidget(self.label_230, 8, 0, 1, 1)
        self.label_228 = QtWidgets.QLabel(self.groupBox_5)
        self.label_228.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_228.setObjectName("label_228")
        self.gridLayout_3.addWidget(self.label_228, 6, 0, 1, 1)
        self.w_box_2 = QtWidgets.QLineEdit(self.groupBox_5)
        self.w_box_2.setEnabled(True)
        self.w_box_2.setReadOnly(False)
        self.w_box_2.setPlaceholderText("")
        self.w_box_2.setObjectName("w_box_2")
        self.gridLayout_3.addWidget(self.w_box_2, 2, 1, 1, 1)
        self.label_231 = QtWidgets.QLabel(self.groupBox_5)
        self.label_231.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_231.setObjectName("label_231")
        self.gridLayout_3.addWidget(self.label_231, 2, 0, 1, 1)
        self.label_238 = QtWidgets.QLabel(self.groupBox_5)
        self.label_238.setObjectName("label_238")
        self.gridLayout_3.addWidget(self.label_238, 9, 2, 1, 1)
        self.label_239 = QtWidgets.QLabel(self.groupBox_5)
        self.label_239.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_239.setObjectName("label_239")
        self.gridLayout_3.addWidget(self.label_239, 5, 0, 1, 1)
        self.w_over_h_box_2 = QtWidgets.QLineEdit(self.groupBox_5)
        self.w_over_h_box_2.setEnabled(True)
        self.w_over_h_box_2.setAutoFillBackground(False)
        self.w_over_h_box_2.setReadOnly(False)
        self.w_over_h_box_2.setPlaceholderText("")
        self.w_over_h_box_2.setObjectName("w_over_h_box_2")
        self.gridLayout_3.addWidget(self.w_over_h_box_2, 5, 1, 1, 1)
        self.lambda_over_lambda_tem_box_2 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lambda_over_lambda_tem_box_2.setEnabled(True)
        self.lambda_over_lambda_tem_box_2.setReadOnly(True)
        self.lambda_over_lambda_tem_box_2.setPlaceholderText("")
        self.lambda_over_lambda_tem_box_2.setObjectName("lambda_over_lambda_tem_box_2")
        self.gridLayout_3.addWidget(self.lambda_over_lambda_tem_box_2, 8, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem12, 8, 3, 1, 1)
        self.length_box_2 = QtWidgets.QLineEdit(self.groupBox_5)
        self.length_box_2.setEnabled(True)
        self.length_box_2.setReadOnly(False)
        self.length_box_2.setPlaceholderText("")
        self.length_box_2.setObjectName("length_box_2")
        self.gridLayout_3.addWidget(self.length_box_2, 1, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem13, 0, 1, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem14, 12, 1, 1, 1)
        self.label_236 = QtWidgets.QLabel(self.groupBox_5)
        self.label_236.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_236.setObjectName("label_236")
        self.gridLayout_3.addWidget(self.label_236, 9, 0, 1, 1)
        self.label_233 = QtWidgets.QLabel(self.groupBox_5)
        self.label_233.setObjectName("label_233")
        self.gridLayout_3.addWidget(self.label_233, 6, 2, 1, 1)
        self.z0box_2 = QtWidgets.QLineEdit(self.groupBox_5)
        self.z0box_2.setEnabled(True)
        self.z0box_2.setReadOnly(True)
        self.z0box_2.setPlaceholderText("")
        self.z0box_2.setObjectName("z0box_2")
        self.gridLayout_3.addWidget(self.z0box_2, 6, 1, 1, 1)
        self.epsilon_r_box_2 = QtWidgets.QLineEdit(self.groupBox_5)
        self.epsilon_r_box_2.setEnabled(True)
        self.epsilon_r_box_2.setObjectName("epsilon_r_box_2")
        self.gridLayout_3.addWidget(self.epsilon_r_box_2, 4, 1, 1, 1)
        self.label_229 = QtWidgets.QLabel(self.groupBox_5)
        self.label_229.setObjectName("label_229")
        self.gridLayout_3.addWidget(self.label_229, 10, 2, 1, 1)
        self.lambda_box_2 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lambda_box_2.setEnabled(True)
        self.lambda_box_2.setReadOnly(True)
        self.lambda_box_2.setPlaceholderText("")
        self.lambda_box_2.setObjectName("lambda_box_2")
        self.gridLayout_3.addWidget(self.lambda_box_2, 10, 1, 1, 1)
        self.label_226 = QtWidgets.QLabel(self.groupBox_5)
        self.label_226.setObjectName("label_226")
        self.gridLayout_3.addWidget(self.label_226, 7, 2, 1, 1)
        self.label_232 = QtWidgets.QLabel(self.groupBox_5)
        self.label_232.setObjectName("label_232")
        self.gridLayout_3.addWidget(self.label_232, 3, 2, 1, 1)
        self.label_241 = QtWidgets.QLabel(self.groupBox_5)
        self.label_241.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_241.setObjectName("label_241")
        self.gridLayout_3.addWidget(self.label_241, 3, 0, 1, 1)
        self.verticalLayout_13.addLayout(self.gridLayout_3)
        self.horizontalLayout_4.addWidget(self.groupBox_5)
        self.verticalLayout_15.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem15)
        self.open_plot_button = QtWidgets.QPushButton(self.tab_3)
        self.open_plot_button.setObjectName("open_plot_button")
        self.horizontalLayout.addWidget(self.open_plot_button)
        self.clean_all_button4 = QtWidgets.QPushButton(self.tab_3)
        self.clean_all_button4.setObjectName("clean_all_button4")
        self.horizontalLayout.addWidget(self.clean_all_button4)
        self.show_er_plots_button = QtWidgets.QPushButton(self.tab_3)
        self.show_er_plots_button.setObjectName("show_er_plots_button")
        self.horizontalLayout.addWidget(self.show_er_plots_button)
        self.calculate_button_6 = QtWidgets.QPushButton(self.tab_3)
        self.calculate_button_6.setAutoDefault(False)
        self.calculate_button_6.setDefault(True)
        self.calculate_button_6.setObjectName("calculate_button_6")
        self.horizontalLayout.addWidget(self.calculate_button_6)
        self.verticalLayout_15.addLayout(self.horizontalLayout)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_103 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_103.sizePolicy().hasHeightForWidth())
        self.label_103.setSizePolicy(sizePolicy)
        self.label_103.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_103.setObjectName("label_103")
        self.horizontalLayout_8.addWidget(self.label_103)
        self.Z0_box2 = QtWidgets.QLineEdit(self.groupBox_6)
        self.Z0_box2.setInputMask("")
        self.Z0_box2.setObjectName("Z0_box2")
        self.horizontalLayout_8.addWidget(self.Z0_box2)
        self.label_104 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_104.sizePolicy().hasHeightForWidth())
        self.label_104.setSizePolicy(sizePolicy)
        self.label_104.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_104.setObjectName("label_104")
        self.horizontalLayout_8.addWidget(self.label_104)
        self.verticalLayout_17.addLayout(self.horizontalLayout_8)
        spacerItem16 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_17.addItem(spacerItem16)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.line_8 = QtWidgets.QFrame(self.groupBox_6)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_10.addWidget(self.line_8, 0, 3, 3, 1)
        self.Z_in_box = QtWidgets.QLineEdit(self.groupBox_6)
        self.Z_in_box.setObjectName("Z_in_box")
        self.gridLayout_10.addWidget(self.Z_in_box, 1, 1, 1, 1)
        self.label_268 = QtWidgets.QLabel(self.groupBox_6)
        self.label_268.setEnabled(False)
        self.label_268.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_268.setObjectName("label_268")
        self.gridLayout_10.addWidget(self.label_268, 2, 6, 1, 1)
        self.label_269 = QtWidgets.QLabel(self.groupBox_6)
        self.label_269.setEnabled(False)
        self.label_269.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_269.setObjectName("label_269")
        self.gridLayout_10.addWidget(self.label_269, 2, 4, 1, 1)
        self.label_76 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_76.sizePolicy().hasHeightForWidth())
        self.label_76.setSizePolicy(sizePolicy)
        self.label_76.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_76.setObjectName("label_76")
        self.gridLayout_10.addWidget(self.label_76, 1, 0, 1, 1)
        self.label_91 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_91.sizePolicy().hasHeightForWidth())
        self.label_91.setSizePolicy(sizePolicy)
        self.label_91.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_91.setObjectName("label_91")
        self.gridLayout_10.addWidget(self.label_91, 1, 2, 1, 1)
        self.Z_out_box = QtWidgets.QLineEdit(self.groupBox_6)
        self.Z_out_box.setObjectName("Z_out_box")
        self.gridLayout_10.addWidget(self.Z_out_box, 2, 1, 1, 1)
        self.label_92 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_92.sizePolicy().hasHeightForWidth())
        self.label_92.setSizePolicy(sizePolicy)
        self.label_92.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_92.setObjectName("label_92")
        self.gridLayout_10.addWidget(self.label_92, 2, 2, 1, 1)
        self.ZS_box_8 = QtWidgets.QLineEdit(self.groupBox_6)
        self.ZS_box_8.setEnabled(False)
        self.ZS_box_8.setObjectName("ZS_box_8")
        self.gridLayout_10.addWidget(self.ZS_box_8, 2, 7, 1, 1)
        self.label_267 = QtWidgets.QLabel(self.groupBox_6)
        self.label_267.setEnabled(False)
        self.label_267.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_267.setObjectName("label_267")
        self.gridLayout_10.addWidget(self.label_267, 1, 4, 1, 1)
        self.label_266 = QtWidgets.QLabel(self.groupBox_6)
        self.label_266.setEnabled(False)
        self.label_266.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_266.setObjectName("label_266")
        self.gridLayout_10.addWidget(self.label_266, 1, 6, 1, 1)
        self.ZS_box_6 = QtWidgets.QLineEdit(self.groupBox_6)
        self.ZS_box_6.setEnabled(False)
        self.ZS_box_6.setObjectName("ZS_box_6")
        self.gridLayout_10.addWidget(self.ZS_box_6, 1, 7, 1, 1)
        self.ZS_box_9 = QtWidgets.QLineEdit(self.groupBox_6)
        self.ZS_box_9.setEnabled(False)
        self.ZS_box_9.setObjectName("ZS_box_9")
        self.gridLayout_10.addWidget(self.ZS_box_9, 1, 5, 1, 1)
        self.ZS_box_7 = QtWidgets.QLineEdit(self.groupBox_6)
        self.ZS_box_7.setEnabled(False)
        self.ZS_box_7.setObjectName("ZS_box_7")
        self.gridLayout_10.addWidget(self.ZS_box_7, 2, 5, 1, 1)
        self.label_75 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_75.sizePolicy().hasHeightForWidth())
        self.label_75.setSizePolicy(sizePolicy)
        self.label_75.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_75.setObjectName("label_75")
        self.gridLayout_10.addWidget(self.label_75, 2, 0, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_6)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout_10.addWidget(self.radioButton_2, 0, 5, 1, 3)
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_6)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_10.addWidget(self.radioButton, 0, 1, 1, 2)
        self.verticalLayout_17.addLayout(self.gridLayout_10)
        self.horizontalLayout_3.addLayout(self.verticalLayout_17)
        self.verticalLayout_18.addWidget(self.groupBox_6)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem17)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_99 = QtWidgets.QLabel(self.tab_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_99.sizePolicy().hasHeightForWidth())
        self.label_99.setSizePolicy(sizePolicy)
        self.label_99.setMaximumSize(QtCore.QSize(16777215, 21))
        self.label_99.setAlignment(QtCore.Qt.AlignCenter)
        self.label_99.setObjectName("label_99")
        self.gridLayout_11.addWidget(self.label_99, 0, 1, 1, 1)
        self.label_100 = QtWidgets.QLabel(self.tab_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_100.sizePolicy().hasHeightForWidth())
        self.label_100.setSizePolicy(sizePolicy)
        self.label_100.setMaximumSize(QtCore.QSize(16777215, 21))
        self.label_100.setAlignment(QtCore.Qt.AlignCenter)
        self.label_100.setObjectName("label_100")
        self.gridLayout_11.addWidget(self.label_100, 0, 2, 1, 1)
        self.label_94 = QtWidgets.QLabel(self.tab_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_94.sizePolicy().hasHeightForWidth())
        self.label_94.setSizePolicy(sizePolicy)
        self.label_94.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_94.setObjectName("label_94")
        self.gridLayout_11.addWidget(self.label_94, 1, 0, 1, 1)
        self.z_in_box_2 = QtWidgets.QTextBrowser(self.tab_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.z_in_box_2.sizePolicy().hasHeightForWidth())
        self.z_in_box_2.setSizePolicy(sizePolicy)
        self.z_in_box_2.setMaximumSize(QtCore.QSize(16777215, 21))
        self.z_in_box_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.z_in_box_2.setObjectName("z_in_box_2")
        self.gridLayout_11.addWidget(self.z_in_box_2, 1, 1, 1, 1)
        self.z_in_box_5 = QtWidgets.QTextBrowser(self.tab_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.z_in_box_5.sizePolicy().hasHeightForWidth())
        self.z_in_box_5.setSizePolicy(sizePolicy)
        self.z_in_box_5.setMaximumSize(QtCore.QSize(16777215, 21))
        self.z_in_box_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.z_in_box_5.setObjectName("z_in_box_5")
        self.gridLayout_11.addWidget(self.z_in_box_5, 1, 2, 1, 1)
        self.label_93 = QtWidgets.QLabel(self.tab_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_93.sizePolicy().hasHeightForWidth())
        self.label_93.setSizePolicy(sizePolicy)
        self.label_93.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_93.setObjectName("label_93")
        self.gridLayout_11.addWidget(self.label_93, 2, 0, 1, 1)
        self.z_in_box = QtWidgets.QTextBrowser(self.tab_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.z_in_box.sizePolicy().hasHeightForWidth())
        self.z_in_box.setSizePolicy(sizePolicy)
        self.z_in_box.setMaximumSize(QtCore.QSize(16777215, 21))
        self.z_in_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.z_in_box.setObjectName("z_in_box")
        self.gridLayout_11.addWidget(self.z_in_box, 2, 1, 1, 1)
        self.z_out_box = QtWidgets.QTextBrowser(self.tab_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.z_out_box.sizePolicy().hasHeightForWidth())
        self.z_out_box.setSizePolicy(sizePolicy)
        self.z_out_box.setMaximumSize(QtCore.QSize(16777215, 21))
        self.z_out_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.z_out_box.setObjectName("z_out_box")
        self.gridLayout_11.addWidget(self.z_out_box, 2, 2, 1, 1)
        self.label_96 = QtWidgets.QLabel(self.tab_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_96.sizePolicy().hasHeightForWidth())
        self.label_96.setSizePolicy(sizePolicy)
        self.label_96.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_96.setObjectName("label_96")
        self.gridLayout_11.addWidget(self.label_96, 3, 0, 1, 1)
        self.gamma_zin_box = QtWidgets.QTextBrowser(self.tab_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gamma_zin_box.sizePolicy().hasHeightForWidth())
        self.gamma_zin_box.setSizePolicy(sizePolicy)
        self.gamma_zin_box.setMaximumSize(QtCore.QSize(16777215, 21))
        self.gamma_zin_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.gamma_zin_box.setObjectName("gamma_zin_box")
        self.gridLayout_11.addWidget(self.gamma_zin_box, 3, 1, 1, 1)
        self.gamma_zout_box = QtWidgets.QTextBrowser(self.tab_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gamma_zout_box.sizePolicy().hasHeightForWidth())
        self.gamma_zout_box.setSizePolicy(sizePolicy)
        self.gamma_zout_box.setMaximumSize(QtCore.QSize(16777215, 21))
        self.gamma_zout_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.gamma_zout_box.setObjectName("gamma_zout_box")
        self.gridLayout_11.addWidget(self.gamma_zout_box, 3, 2, 1, 1)
        self.label_97 = QtWidgets.QLabel(self.tab_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_97.sizePolicy().hasHeightForWidth())
        self.label_97.setSizePolicy(sizePolicy)
        self.label_97.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_97.setObjectName("label_97")
        self.gridLayout_11.addWidget(self.label_97, 4, 0, 1, 1)
        self.lambda_tick_zin_box = QtWidgets.QTextBrowser(self.tab_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lambda_tick_zin_box.sizePolicy().hasHeightForWidth())
        self.lambda_tick_zin_box.setSizePolicy(sizePolicy)
        self.lambda_tick_zin_box.setMaximumSize(QtCore.QSize(16777215, 21))
        self.lambda_tick_zin_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lambda_tick_zin_box.setObjectName("lambda_tick_zin_box")
        self.gridLayout_11.addWidget(self.lambda_tick_zin_box, 4, 1, 1, 1)
        self.lambda_tick_zout_box = QtWidgets.QTextBrowser(self.tab_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lambda_tick_zout_box.sizePolicy().hasHeightForWidth())
        self.lambda_tick_zout_box.setSizePolicy(sizePolicy)
        self.lambda_tick_zout_box.setMaximumSize(QtCore.QSize(16777215, 21))
        self.lambda_tick_zout_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lambda_tick_zout_box.setObjectName("lambda_tick_zout_box")
        self.gridLayout_11.addWidget(self.lambda_tick_zout_box, 4, 2, 1, 1)
        self.verticalLayout_18.addLayout(self.gridLayout_11)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_18.addItem(spacerItem18)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem19)
        self.Show_Smith = QtWidgets.QPushButton(self.tab_6)
        self.Show_Smith.setObjectName("Show_Smith")
        self.horizontalLayout_5.addWidget(self.Show_Smith)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem20)
        self.clean_all_button213 = QtWidgets.QPushButton(self.tab_6)
        self.clean_all_button213.setObjectName("clean_all_button213")
        self.horizontalLayout_5.addWidget(self.clean_all_button213)
        self.Calculate_quarter = QtWidgets.QPushButton(self.tab_6)
        self.Calculate_quarter.setDefault(True)
        self.Calculate_quarter.setObjectName("Calculate_quarter")
        self.horizontalLayout_5.addWidget(self.Calculate_quarter)
        self.verticalLayout_18.addLayout(self.horizontalLayout_5)
        self.verticalLayout_19.addLayout(self.verticalLayout_18)
        self.tabWidget_2.addTab(self.tab_6, "Smith Chart")
        self.verticalLayout_16.addWidget(self.tabWidget_2)
        self.tabWidget_3.addTab(self.tab_7, "")
        self.gridLayout_4.addWidget(self.tabWidget_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actiondsd = QtWidgets.QAction(MainWindow)
        self.actiondsd.setObjectName("actiondsd")

        self.retranslateUi(MainWindow)
        self.tabWidget_3.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt;\">L-section Matching Network</span></p></body></html>"))
        self.label_83.setText(_translate("MainWindow", "C<sub>1</sub>"))
        self.label_24.setText(_translate("MainWindow", "B<sub>1</sub>"))
        self.label_23.setText(_translate("MainWindow", "X<sub>1</sub>"))
        self.label_110.setText(_translate("MainWindow", "Ω"))
        self.label_87.setText(_translate("MainWindow", "C<sub>2</sub>"))
        self.label_74.setText(_translate("MainWindow", "B<sub>2</sub>"))
        self.label_88.setText(_translate("MainWindow", "L<sub>2</sub>"))
        self.label_111.setText(_translate("MainWindow", "mS"))
        self.label_115.setText(_translate("MainWindow", "mS"))
        self.label_84.setText(_translate("MainWindow", "L<sub>1</sub>"))
        self.label_114.setText(_translate("MainWindow", "Ω"))
        self.label_80.setText(_translate("MainWindow", "X<sub>2</sub>"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Impedance [Ω]"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Admittance [mS]"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Impedance [Ω]"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Admittance [mS]"))
        self.label_73.setText(_translate("MainWindow", "Output (Z<sub>0</sub>)"))
        self.label_72.setText(_translate("MainWindow", "Input (Z<sub>L</sub>)"))
        self.label_70.setText(_translate("MainWindow", "f<sub>0</sub>"))
        self.label_7.setText(_translate("MainWindow", "MHz"))
        self.label_15.setText(_translate("MainWindow", "Input admittance (Y<sub>L</sub>)"))
        self.label_106.setText(_translate("MainWindow", "Ω"))
        self.label_14.setText(_translate("MainWindow", "Input impedance (Z<sub>L</sub>)"))
        self.label_107.setText(_translate("MainWindow", "mS"))
        self.label_16.setText(_translate("MainWindow", "Output impedance (Z<sub>0</sub>)"))
        self.label_108.setText(_translate("MainWindow", "Ω"))
        self.label_17.setText(_translate("MainWindow", "Output admittance (Y<sub>0</sub>)"))
        self.label_109.setText(_translate("MainWindow", "mS"))
        self.open_pdf_sketch_button.setText(_translate("MainWindow", "Open schematic"))
        self.plot.setText(_translate("MainWindow", "Show Γ Plot"))
        self.Clean_all_button_3.setText(_translate("MainWindow", "Clean All"))
        self.Calculate_button_3.setText(_translate("MainWindow", "Calculate"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_4), _translate("MainWindow", "Lumped parameters"))
        self.groupBox_4.setTitle(_translate("MainWindow", "l(λ) to length"))
        self.label_222.setText(_translate("MainWindow", "mm"))
        self.label_224.setText(_translate("MainWindow", "<html><head/><body><p>λ/λ<span style=\" vertical-align:sub;\">TEM</span></p></body></html>"))
        self.label_212.setText(_translate("MainWindow", "mm"))
        self.label_207.setText(_translate("MainWindow", "<html><head/><body><p>λ<span style=\" vertical-align:sub;\">TEM </span>(f,ε<span style=\" vertical-align:sub;\">r</span>)</p></body></html>"))
        self.label_206.setText(_translate("MainWindow", "MHz"))
        self.label_202.setText(_translate("MainWindow", "mm"))
        self.z0box.setPlaceholderText(_translate("MainWindow", "Check the plots in order to choose a plausible value"))
        self.epsilon_r_box.setPlaceholderText(_translate("MainWindow", "{2, 4, 6, 8, 10, 12}"))
        self.label_223.setText(_translate("MainWindow", "<html><head/><body><p>length</p></body></html>"))
        self.label_218.setText(_translate("MainWindow", "cm"))
        self.label_216.setText(_translate("MainWindow", "cm"))
        self.label_204.setText(_translate("MainWindow", "Ω"))
        self.label_210.setText(_translate("MainWindow", "<html><head/><body><p>w/h</p></body></html>"))
        self.label_199.setText(_translate("MainWindow", "<html><head/><body><p>f</p></body></html>"))
        self.label_198.setText(_translate("MainWindow", "<html><head/><body><p>h</p></body></html>"))
        self.label_215.setText(_translate("MainWindow", "<html><head/><body><p>w</p></body></html>"))
        self.label_191.setText(_translate("MainWindow", "<html><head/><body><p>ε<span style=\" vertical-align:sub;\">r</span></p></body></html>"))
        self.label_203.setText(_translate("MainWindow", "<html><head/><body><p>Z<span style=\" vertical-align:sub;\">0</span></p></body></html>"))
        self.label_209.setText(_translate("MainWindow", "<html><head/><body><p>l(λ)</p></body></html>"))
        self.label_220.setText(_translate("MainWindow", "<html><head/><body><p>λ</p></body></html>"))
        self.groupBox_5.setTitle(_translate("MainWindow", "length to l(λ)"))
        self.label_242.setText(_translate("MainWindow", "<html><head/><body><p>λ</p></body></html>"))
        self.label_225.setText(_translate("MainWindow", "mm"))
        self.label_240.setText(_translate("MainWindow", "mm"))
        self.label_237.setText(_translate("MainWindow", "<html><head/><body><p>length</p></body></html>"))
        self.label_235.setText(_translate("MainWindow", "<html><head/><body><p>ε<span style=\" vertical-align:sub;\">r</span></p></body></html>"))
        self.label_227.setText(_translate("MainWindow", "<html><head/><body><p>l(λ)</p></body></html>"))
        self.label_234.setText(_translate("MainWindow", "<html><head/><body><p>f</p></body></html>"))
        self.label_230.setText(_translate("MainWindow", "<html><head/><body><p>λ/λ<span style=\" vertical-align:sub;\">TEM</span></p></body></html>"))
        self.label_228.setText(_translate("MainWindow", "<html><head/><body><p>Z<span style=\" vertical-align:sub;\">0</span></p></body></html>"))
        self.label_231.setText(_translate("MainWindow", "<html><head/><body><p>w</p></body></html>"))
        self.label_238.setText(_translate("MainWindow", "cm"))
        self.label_239.setText(_translate("MainWindow", "<html><head/><body><p>w/h</p></body></html>"))
        self.label_236.setText(_translate("MainWindow", "<html><head/><body><p>λ<span style=\" vertical-align:sub;\">TEM </span>(f,ε<span style=\" vertical-align:sub;\">r</span>)</p></body></html>"))
        self.label_233.setText(_translate("MainWindow", "Ω"))
        self.epsilon_r_box_2.setPlaceholderText(_translate("MainWindow", "{2, 4, 6, 8, 10, 12}"))
        self.label_229.setText(_translate("MainWindow", "cm"))
        self.label_226.setText(_translate("MainWindow", "MHz"))
        self.label_232.setText(_translate("MainWindow", "mm"))
        self.label_241.setText(_translate("MainWindow", "<html><head/><body><p>h</p></body></html>"))
        self.open_plot_button.setText(_translate("MainWindow", "Open PDF plot"))
        self.clean_all_button4.setText(_translate("MainWindow", "Clean All"))
        self.show_er_plots_button.setText(_translate("MainWindow", "Show Plots"))
        self.calculate_button_6.setText(_translate("MainWindow", "Calculate"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Microstrip"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Input initial and final impedance as either Z or Γ"))
        self.label_103.setText(_translate("MainWindow", "<html><head/><body><p>Z<span style=\" vertical-align:sub;\">0</span></p></body></html>"))
        self.Z0_box2.setText(_translate("MainWindow", "50"))
        self.label_104.setText(_translate("MainWindow", "<html><head/><body><p>Ω</p></body></html>"))
        self.label_268.setText(_translate("MainWindow", "<html><head/><body><p>∠Γ(Z<span style=\" vertical-align:sub;\">L</span>\')</p></body></html>"))
        self.label_269.setText(_translate("MainWindow", "<html><head/><body><p>|Γ|(Z<span style=\" vertical-align:sub;\">L</span>\')</p></body></html>"))
        self.label_76.setText(_translate("MainWindow", "Input (Z<sub>L</sub>)"))
        self.label_91.setText(_translate("MainWindow", "<html><head/><body><p>Ω</p></body></html>"))
        self.label_92.setText(_translate("MainWindow", "<html><head/><body><p>Ω</p></body></html>"))
        self.label_267.setText(_translate("MainWindow", "<html><head/><body><p>|Γ|(Z<span style=\" vertical-align:sub;\">L</span>)</p></body></html>"))
        self.label_266.setText(_translate("MainWindow", "<html><head/><body><p>∠Γ(Z<span style=\" vertical-align:sub;\">L</span>)</p></body></html>"))
        self.label_75.setText(_translate("MainWindow", "<html><head/><body><p>Output (Z<span style=\" vertical-align:sub;\">L</span>\')</p></body></html>"))
        self.radioButton_2.setText(_translate("MainWindow", "Input as Γ"))
        self.radioButton.setText(_translate("MainWindow", "Input as Z"))
        self.label_99.setText(_translate("MainWindow", "<html><head/><body><p>Z<span style=\" vertical-align:sub;\">L</span></p></body></html>"))
        self.label_100.setText(_translate("MainWindow", "<html><head/><body><p>Z<span style=\" vertical-align:sub;\">L</span>\'</p></body></html>"))
        self.label_94.setText(_translate("MainWindow", "<html><head/><body><p>Actual impedance</p></body></html>"))
        self.label_93.setText(_translate("MainWindow", "<html><head/><body><p>Normalized impedance</p></body></html>"))
        self.label_96.setText(_translate("MainWindow", "<html><head/><body><p>Γ</p></body></html>"))
        self.label_97.setText(_translate("MainWindow", "<html><head/><body><p>corresponding λ tick</p></body></html>"))
        self.Show_Smith.setText(_translate("MainWindow", "Open Smith Chart"))
        self.clean_all_button213.setText(_translate("MainWindow", "Clean All"))
        self.Calculate_quarter.setText(_translate("MainWindow", "Calculate"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), _translate("MainWindow", "Microwaves"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actiondsd.setText(_translate("MainWindow", "dsd"))

