# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../../../ui/microstrip_matching_window.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(824, 540)
        MainWindow.setWindowTitle("Microstrip Matching")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_222 = QtWidgets.QLabel(self.groupBox_4)
        self.label_222.setObjectName("label_222")
        self.gridLayout.addWidget(self.label_222, 10, 4, 1, 1)
        self.w_over_h_box = QtWidgets.QLineEdit(self.groupBox_4)
        self.w_over_h_box.setEnabled(True)
        self.w_over_h_box.setAutoFillBackground(False)
        self.w_over_h_box.setReadOnly(True)
        self.w_over_h_box.setPlaceholderText("")
        self.w_over_h_box.setObjectName("w_over_h_box")
        self.gridLayout.addWidget(self.w_over_h_box, 6, 3, 1, 1)
        self.w_box = QtWidgets.QLineEdit(self.groupBox_4)
        self.w_box.setEnabled(True)
        self.w_box.setReadOnly(False)
        self.w_box.setPlaceholderText("")
        self.w_box.setObjectName("w_box")
        self.gridLayout.addWidget(self.w_box, 3, 3, 1, 1)
        self.label_224 = QtWidgets.QLabel(self.groupBox_4)
        self.label_224.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_224.setObjectName("label_224")
        self.gridLayout.addWidget(self.label_224, 7, 1, 1, 2)
        self.lambda_over_lambda_tem_box = QtWidgets.QLineEdit(self.groupBox_4)
        self.lambda_over_lambda_tem_box.setEnabled(True)
        self.lambda_over_lambda_tem_box.setReadOnly(True)
        self.lambda_over_lambda_tem_box.setPlaceholderText("")
        self.lambda_over_lambda_tem_box.setObjectName("lambda_over_lambda_tem_box")
        self.gridLayout.addWidget(self.lambda_over_lambda_tem_box, 7, 3, 1, 1)
        self.label_212 = QtWidgets.QLabel(self.groupBox_4)
        self.label_212.setObjectName("label_212")
        self.gridLayout.addWidget(self.label_212, 3, 4, 1, 1)
        self.label_207 = QtWidgets.QLabel(self.groupBox_4)
        self.label_207.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_207.setObjectName("label_207")
        self.gridLayout.addWidget(self.label_207, 8, 1, 1, 2)
        self.lambda_tem_box = QtWidgets.QLineEdit(self.groupBox_4)
        self.lambda_tem_box.setEnabled(True)
        self.lambda_tem_box.setReadOnly(True)
        self.lambda_tem_box.setPlaceholderText("")
        self.lambda_tem_box.setObjectName("lambda_tem_box")
        self.gridLayout.addWidget(self.lambda_tem_box, 8, 3, 1, 1)
        self.length_box = QtWidgets.QLineEdit(self.groupBox_4)
        self.length_box.setEnabled(True)
        self.length_box.setReadOnly(True)
        self.length_box.setPlaceholderText("")
        self.length_box.setObjectName("length_box")
        self.gridLayout.addWidget(self.length_box, 10, 3, 1, 1)
        self.label_206 = QtWidgets.QLabel(self.groupBox_4)
        self.label_206.setObjectName("label_206")
        self.gridLayout.addWidget(self.label_206, 5, 4, 1, 1)
        self.f_box_3 = QtWidgets.QLineEdit(self.groupBox_4)
        self.f_box_3.setPlaceholderText("")
        self.f_box_3.setObjectName("f_box_3")
        self.gridLayout.addWidget(self.f_box_3, 5, 3, 1, 1)
        self.label_202 = QtWidgets.QLabel(self.groupBox_4)
        self.label_202.setObjectName("label_202")
        self.gridLayout.addWidget(self.label_202, 4, 4, 1, 1)
        self.h_box = QtWidgets.QLineEdit(self.groupBox_4)
        self.h_box.setPlaceholderText("")
        self.h_box.setObjectName("h_box")
        self.gridLayout.addWidget(self.h_box, 4, 3, 1, 1)
        self.z0box = QtWidgets.QLineEdit(self.groupBox_4)
        self.z0box.setEnabled(True)
        self.z0box.setObjectName("z0box")
        self.gridLayout.addWidget(self.z0box, 1, 3, 1, 1)
        self.epsilon_r_box = QtWidgets.QLineEdit(self.groupBox_4)
        self.epsilon_r_box.setEnabled(True)
        self.epsilon_r_box.setObjectName("epsilon_r_box")
        self.gridLayout.addWidget(self.epsilon_r_box, 2, 3, 1, 1)
        self.label_223 = QtWidgets.QLabel(self.groupBox_4)
        self.label_223.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_223.setObjectName("label_223")
        self.gridLayout.addWidget(self.label_223, 10, 1, 1, 2)
        self.label_218 = QtWidgets.QLabel(self.groupBox_4)
        self.label_218.setObjectName("label_218")
        self.gridLayout.addWidget(self.label_218, 9, 4, 1, 1)
        self.lambda_box = QtWidgets.QLineEdit(self.groupBox_4)
        self.lambda_box.setEnabled(True)
        self.lambda_box.setReadOnly(True)
        self.lambda_box.setPlaceholderText("")
        self.lambda_box.setObjectName("lambda_box")
        self.gridLayout.addWidget(self.lambda_box, 9, 3, 1, 1)
        self.label_216 = QtWidgets.QLabel(self.groupBox_4)
        self.label_216.setObjectName("label_216")
        self.gridLayout.addWidget(self.label_216, 8, 4, 1, 1)
        self.label_204 = QtWidgets.QLabel(self.groupBox_4)
        self.label_204.setObjectName("label_204")
        self.gridLayout.addWidget(self.label_204, 1, 4, 1, 1)
        self.l_lambda_box = QtWidgets.QLineEdit(self.groupBox_4)
        self.l_lambda_box.setPlaceholderText("")
        self.l_lambda_box.setObjectName("l_lambda_box")
        self.gridLayout.addWidget(self.l_lambda_box, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 5, 0, 1, 1)
        self.label_210 = QtWidgets.QLabel(self.groupBox_4)
        self.label_210.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_210.setObjectName("label_210")
        self.gridLayout.addWidget(self.label_210, 6, 1, 1, 2)
        self.label_199 = QtWidgets.QLabel(self.groupBox_4)
        self.label_199.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_199.setObjectName("label_199")
        self.gridLayout.addWidget(self.label_199, 5, 1, 1, 2)
        self.label_198 = QtWidgets.QLabel(self.groupBox_4)
        self.label_198.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_198.setObjectName("label_198")
        self.gridLayout.addWidget(self.label_198, 4, 1, 1, 2)
        self.label_215 = QtWidgets.QLabel(self.groupBox_4)
        self.label_215.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_215.setObjectName("label_215")
        self.gridLayout.addWidget(self.label_215, 3, 1, 1, 2)
        self.label_191 = QtWidgets.QLabel(self.groupBox_4)
        self.label_191.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_191.setObjectName("label_191")
        self.gridLayout.addWidget(self.label_191, 2, 1, 1, 2)
        self.label_203 = QtWidgets.QLabel(self.groupBox_4)
        self.label_203.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_203.setObjectName("label_203")
        self.gridLayout.addWidget(self.label_203, 1, 1, 1, 2)
        self.label_209 = QtWidgets.QLabel(self.groupBox_4)
        self.label_209.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_209.setObjectName("label_209")
        self.gridLayout.addWidget(self.label_209, 0, 1, 1, 2)
        self.label_220 = QtWidgets.QLabel(self.groupBox_4)
        self.label_220.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_220.setObjectName("label_220")
        self.gridLayout.addWidget(self.label_220, 9, 1, 1, 2)
        self.verticalLayout_14.addLayout(self.gridLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem2)
        self.verticalLayout_30.addLayout(self.verticalLayout_14)
        self.horizontalLayout_4.addWidget(self.groupBox_4)
        spacerItem3 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_242 = QtWidgets.QLabel(self.groupBox_5)
        self.label_242.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_242.setObjectName("label_242")
        self.gridLayout_3.addWidget(self.label_242, 10, 0, 1, 1)
        self.label_225 = QtWidgets.QLabel(self.groupBox_5)
        self.label_225.setObjectName("label_225")
        self.gridLayout_3.addWidget(self.label_225, 1, 2, 1, 1)
        self.h_box_2 = QtWidgets.QLineEdit(self.groupBox_5)
        self.h_box_2.setPlaceholderText("")
        self.h_box_2.setObjectName("h_box_2")
        self.gridLayout_3.addWidget(self.h_box_2, 3, 1, 1, 1)
        self.f_box_4 = QtWidgets.QLineEdit(self.groupBox_5)
        self.f_box_4.setPlaceholderText("")
        self.f_box_4.setObjectName("f_box_4")
        self.gridLayout_3.addWidget(self.f_box_4, 7, 1, 1, 1)
        self.lambda_tem_box_2 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lambda_tem_box_2.setEnabled(True)
        self.lambda_tem_box_2.setReadOnly(True)
        self.lambda_tem_box_2.setPlaceholderText("")
        self.lambda_tem_box_2.setObjectName("lambda_tem_box_2")
        self.gridLayout_3.addWidget(self.lambda_tem_box_2, 9, 1, 1, 1)
        self.label_240 = QtWidgets.QLabel(self.groupBox_5)
        self.label_240.setObjectName("label_240")
        self.gridLayout_3.addWidget(self.label_240, 2, 2, 1, 1)
        self.label_237 = QtWidgets.QLabel(self.groupBox_5)
        self.label_237.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_237.setObjectName("label_237")
        self.gridLayout_3.addWidget(self.label_237, 1, 0, 1, 1)
        self.label_235 = QtWidgets.QLabel(self.groupBox_5)
        self.label_235.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_235.setObjectName("label_235")
        self.gridLayout_3.addWidget(self.label_235, 4, 0, 1, 1)
        self.label_227 = QtWidgets.QLabel(self.groupBox_5)
        self.label_227.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_227.setObjectName("label_227")
        self.gridLayout_3.addWidget(self.label_227, 11, 0, 1, 1)
        self.l_lambda_box_2 = QtWidgets.QLineEdit(self.groupBox_5)
        self.l_lambda_box_2.setReadOnly(True)
        self.l_lambda_box_2.setPlaceholderText("")
        self.l_lambda_box_2.setObjectName("l_lambda_box_2")
        self.gridLayout_3.addWidget(self.l_lambda_box_2, 11, 1, 1, 1)
        self.label_234 = QtWidgets.QLabel(self.groupBox_5)
        self.label_234.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_234.setObjectName("label_234")
        self.gridLayout_3.addWidget(self.label_234, 7, 0, 1, 1)
        self.label_230 = QtWidgets.QLabel(self.groupBox_5)
        self.label_230.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_230.setObjectName("label_230")
        self.gridLayout_3.addWidget(self.label_230, 8, 0, 1, 1)
        self.label_228 = QtWidgets.QLabel(self.groupBox_5)
        self.label_228.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_228.setObjectName("label_228")
        self.gridLayout_3.addWidget(self.label_228, 6, 0, 1, 1)
        self.w_box_2 = QtWidgets.QLineEdit(self.groupBox_5)
        self.w_box_2.setEnabled(True)
        self.w_box_2.setReadOnly(False)
        self.w_box_2.setPlaceholderText("")
        self.w_box_2.setObjectName("w_box_2")
        self.gridLayout_3.addWidget(self.w_box_2, 2, 1, 1, 1)
        self.label_231 = QtWidgets.QLabel(self.groupBox_5)
        self.label_231.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_231.setObjectName("label_231")
        self.gridLayout_3.addWidget(self.label_231, 2, 0, 1, 1)
        self.label_238 = QtWidgets.QLabel(self.groupBox_5)
        self.label_238.setObjectName("label_238")
        self.gridLayout_3.addWidget(self.label_238, 9, 2, 1, 1)
        self.label_239 = QtWidgets.QLabel(self.groupBox_5)
        self.label_239.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_239.setObjectName("label_239")
        self.gridLayout_3.addWidget(self.label_239, 5, 0, 1, 1)
        self.w_over_h_box_2 = QtWidgets.QLineEdit(self.groupBox_5)
        self.w_over_h_box_2.setEnabled(True)
        self.w_over_h_box_2.setAutoFillBackground(False)
        self.w_over_h_box_2.setReadOnly(False)
        self.w_over_h_box_2.setPlaceholderText("")
        self.w_over_h_box_2.setObjectName("w_over_h_box_2")
        self.gridLayout_3.addWidget(self.w_over_h_box_2, 5, 1, 1, 1)
        self.lambda_over_lambda_tem_box_2 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lambda_over_lambda_tem_box_2.setEnabled(True)
        self.lambda_over_lambda_tem_box_2.setReadOnly(True)
        self.lambda_over_lambda_tem_box_2.setPlaceholderText("")
        self.lambda_over_lambda_tem_box_2.setObjectName("lambda_over_lambda_tem_box_2")
        self.gridLayout_3.addWidget(self.lambda_over_lambda_tem_box_2, 8, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 8, 3, 1, 1)
        self.length_box_2 = QtWidgets.QLineEdit(self.groupBox_5)
        self.length_box_2.setEnabled(True)
        self.length_box_2.setReadOnly(False)
        self.length_box_2.setPlaceholderText("")
        self.length_box_2.setObjectName("length_box_2")
        self.gridLayout_3.addWidget(self.length_box_2, 1, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem5, 0, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem6, 12, 1, 1, 1)
        self.label_236 = QtWidgets.QLabel(self.groupBox_5)
        self.label_236.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_236.setObjectName("label_236")
        self.gridLayout_3.addWidget(self.label_236, 9, 0, 1, 1)
        self.label_233 = QtWidgets.QLabel(self.groupBox_5)
        self.label_233.setObjectName("label_233")
        self.gridLayout_3.addWidget(self.label_233, 6, 2, 1, 1)
        self.z0box_2 = QtWidgets.QLineEdit(self.groupBox_5)
        self.z0box_2.setEnabled(True)
        self.z0box_2.setReadOnly(True)
        self.z0box_2.setPlaceholderText("")
        self.z0box_2.setObjectName("z0box_2")
        self.gridLayout_3.addWidget(self.z0box_2, 6, 1, 1, 1)
        self.epsilon_r_box_2 = QtWidgets.QLineEdit(self.groupBox_5)
        self.epsilon_r_box_2.setEnabled(True)
        self.epsilon_r_box_2.setObjectName("epsilon_r_box_2")
        self.gridLayout_3.addWidget(self.epsilon_r_box_2, 4, 1, 1, 1)
        self.label_229 = QtWidgets.QLabel(self.groupBox_5)
        self.label_229.setObjectName("label_229")
        self.gridLayout_3.addWidget(self.label_229, 10, 2, 1, 1)
        self.lambda_box_2 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lambda_box_2.setEnabled(True)
        self.lambda_box_2.setReadOnly(True)
        self.lambda_box_2.setPlaceholderText("")
        self.lambda_box_2.setObjectName("lambda_box_2")
        self.gridLayout_3.addWidget(self.lambda_box_2, 10, 1, 1, 1)
        self.label_226 = QtWidgets.QLabel(self.groupBox_5)
        self.label_226.setObjectName("label_226")
        self.gridLayout_3.addWidget(self.label_226, 7, 2, 1, 1)
        self.label_232 = QtWidgets.QLabel(self.groupBox_5)
        self.label_232.setObjectName("label_232")
        self.gridLayout_3.addWidget(self.label_232, 3, 2, 1, 1)
        self.label_241 = QtWidgets.QLabel(self.groupBox_5)
        self.label_241.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_241.setObjectName("label_241")
        self.gridLayout_3.addWidget(self.label_241, 3, 0, 1, 1)
        self.verticalLayout_13.addLayout(self.gridLayout_3)
        self.horizontalLayout_4.addWidget(self.groupBox_5)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.open_plot_button = QtWidgets.QPushButton(self.centralwidget)
        self.open_plot_button.setObjectName("open_plot_button")
        self.horizontalLayout.addWidget(self.open_plot_button)
        self.clean_all_button4 = QtWidgets.QPushButton(self.centralwidget)
        self.clean_all_button4.setObjectName("clean_all_button4")
        self.horizontalLayout.addWidget(self.clean_all_button4)
        self.show_er_plots_button = QtWidgets.QPushButton(self.centralwidget)
        self.show_er_plots_button.setObjectName("show_er_plots_button")
        self.horizontalLayout.addWidget(self.show_er_plots_button)
        self.calculate_button_6 = QtWidgets.QPushButton(self.centralwidget)
        self.calculate_button_6.setAutoDefault(False)
        self.calculate_button_6.setDefault(True)
        self.calculate_button_6.setObjectName("calculate_button_6")
        self.horizontalLayout.addWidget(self.calculate_button_6)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actiondsd = QtWidgets.QAction(MainWindow)
        self.actiondsd.setObjectName("actiondsd")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.l_lambda_box, self.z0box)
        MainWindow.setTabOrder(self.z0box, self.epsilon_r_box)
        MainWindow.setTabOrder(self.epsilon_r_box, self.w_box)
        MainWindow.setTabOrder(self.w_box, self.h_box)
        MainWindow.setTabOrder(self.h_box, self.f_box_3)
        MainWindow.setTabOrder(self.f_box_3, self.length_box_2)
        MainWindow.setTabOrder(self.length_box_2, self.w_box_2)
        MainWindow.setTabOrder(self.w_box_2, self.h_box_2)
        MainWindow.setTabOrder(self.h_box_2, self.epsilon_r_box_2)
        MainWindow.setTabOrder(self.epsilon_r_box_2, self.z0box_2)
        MainWindow.setTabOrder(self.z0box_2, self.f_box_4)
        MainWindow.setTabOrder(self.f_box_4, self.w_over_h_box)
        MainWindow.setTabOrder(self.w_over_h_box, self.lambda_over_lambda_tem_box)
        MainWindow.setTabOrder(self.lambda_over_lambda_tem_box, self.lambda_tem_box)
        MainWindow.setTabOrder(self.lambda_tem_box, self.length_box)
        MainWindow.setTabOrder(self.length_box, self.lambda_box)
        MainWindow.setTabOrder(self.lambda_box, self.lambda_tem_box_2)
        MainWindow.setTabOrder(self.lambda_tem_box_2, self.l_lambda_box_2)
        MainWindow.setTabOrder(self.l_lambda_box_2, self.w_over_h_box_2)
        MainWindow.setTabOrder(self.w_over_h_box_2, self.lambda_over_lambda_tem_box_2)
        MainWindow.setTabOrder(self.lambda_over_lambda_tem_box_2, self.lambda_box_2)
        MainWindow.setTabOrder(self.lambda_box_2, self.open_plot_button)
        MainWindow.setTabOrder(self.open_plot_button, self.clean_all_button4)
        MainWindow.setTabOrder(self.clean_all_button4, self.show_er_plots_button)
        MainWindow.setTabOrder(self.show_er_plots_button, self.calculate_button_6)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.groupBox_4.setTitle(_translate("MainWindow", "l(λ) to length"))
        self.label_222.setText(_translate("MainWindow", "mm"))
        self.label_224.setText(_translate("MainWindow", "<html><head/><body><p>λ/λ<span style=\" vertical-align:sub;\">TEM</span></p></body></html>"))
        self.label_212.setText(_translate("MainWindow", "mm"))
        self.label_207.setText(_translate("MainWindow", "<html><head/><body><p>λ<span style=\" vertical-align:sub;\">TEM </span>(f,ε<span style=\" vertical-align:sub;\">r</span>)</p></body></html>"))
        self.label_206.setText(_translate("MainWindow", "MHz"))
        self.label_202.setText(_translate("MainWindow", "mm"))
        self.z0box.setPlaceholderText(_translate("MainWindow", "Check the plots in order to choose a plausible value"))
        self.epsilon_r_box.setPlaceholderText(_translate("MainWindow", "{2, 4, 6, 8, 10, 12}"))
        self.label_223.setText(_translate("MainWindow", "<html><head/><body><p>length</p></body></html>"))
        self.label_218.setText(_translate("MainWindow", "cm"))
        self.label_216.setText(_translate("MainWindow", "cm"))
        self.label_204.setText(_translate("MainWindow", "Ω"))
        self.label_210.setText(_translate("MainWindow", "<html><head/><body><p>w/h</p></body></html>"))
        self.label_199.setText(_translate("MainWindow", "<html><head/><body><p>f</p></body></html>"))
        self.label_198.setText(_translate("MainWindow", "<html><head/><body><p>h</p></body></html>"))
        self.label_215.setText(_translate("MainWindow", "<html><head/><body><p>w</p></body></html>"))
        self.label_191.setText(_translate("MainWindow", "<html><head/><body><p>ε<span style=\" vertical-align:sub;\">r</span></p></body></html>"))
        self.label_203.setText(_translate("MainWindow", "<html><head/><body><p>Z<span style=\" vertical-align:sub;\">0</span></p></body></html>"))
        self.label_209.setText(_translate("MainWindow", "<html><head/><body><p>l(λ)</p></body></html>"))
        self.label_220.setText(_translate("MainWindow", "<html><head/><body><p>λ</p></body></html>"))
        self.groupBox_5.setTitle(_translate("MainWindow", "length to l(λ)"))
        self.label_242.setText(_translate("MainWindow", "<html><head/><body><p>λ</p></body></html>"))
        self.label_225.setText(_translate("MainWindow", "mm"))
        self.label_240.setText(_translate("MainWindow", "mm"))
        self.label_237.setText(_translate("MainWindow", "<html><head/><body><p>length</p></body></html>"))
        self.label_235.setText(_translate("MainWindow", "<html><head/><body><p>ε<span style=\" vertical-align:sub;\">r</span></p></body></html>"))
        self.label_227.setText(_translate("MainWindow", "<html><head/><body><p>l(λ)</p></body></html>"))
        self.label_234.setText(_translate("MainWindow", "<html><head/><body><p>f</p></body></html>"))
        self.label_230.setText(_translate("MainWindow", "<html><head/><body><p>λ/λ<span style=\" vertical-align:sub;\">TEM</span></p></body></html>"))
        self.label_228.setText(_translate("MainWindow", "<html><head/><body><p>Z<span style=\" vertical-align:sub;\">0</span></p></body></html>"))
        self.label_231.setText(_translate("MainWindow", "<html><head/><body><p>w</p></body></html>"))
        self.label_238.setText(_translate("MainWindow", "cm"))
        self.label_239.setText(_translate("MainWindow", "<html><head/><body><p>w/h</p></body></html>"))
        self.label_236.setText(_translate("MainWindow", "<html><head/><body><p>λ<span style=\" vertical-align:sub;\">TEM </span>(f,ε<span style=\" vertical-align:sub;\">r</span>)</p></body></html>"))
        self.label_233.setText(_translate("MainWindow", "Ω"))
        self.epsilon_r_box_2.setPlaceholderText(_translate("MainWindow", "{2, 4, 6, 8, 10, 12}"))
        self.label_229.setText(_translate("MainWindow", "cm"))
        self.label_226.setText(_translate("MainWindow", "MHz"))
        self.label_232.setText(_translate("MainWindow", "mm"))
        self.label_241.setText(_translate("MainWindow", "<html><head/><body><p>h</p></body></html>"))
        self.open_plot_button.setText(_translate("MainWindow", "Open PDF plot"))
        self.clean_all_button4.setText(_translate("MainWindow", "Clean All"))
        self.show_er_plots_button.setText(_translate("MainWindow", "Show Plots"))
        self.calculate_button_6.setText(_translate("MainWindow", "Calculate"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actiondsd.setText(_translate("MainWindow", "dsd"))

