#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Created on Wed Feb 20 17:23:29 CET 2019

@author(s)   : Francesco Urbani
@file        : integrated_matching.py
@descritpion : 

"""

from PyQt5.QtWidgets import QMainWindow, QAction, QStatusBar, QToolBar, QMenuBar, QMessageBox
from PyQt5.QtGui import QIcon
from PyQt5 import QtCore, QtGui, QtWidgets

from new_update_ui import Ui_MainWindow # main ui window autogenerated by PyQt

import sys
import os 

import check_update




TEXT1 = "<b>A new version  of syRF is available.</b>"
TEXT3 = "<b>Release notes:</b>"

NOTES = """
"""


class mainProgram(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self, parent=None):
        super(mainProgram, self).__init__(parent)
        self.setupUi(self)
        self.setWindowFlags(QtCore.Qt.Window | QtCore.Qt.CustomizeWindowHint | QtCore.Qt.WindowTitleHint | QtCore.Qt.WindowStaysOnTopHint)

        self.remind_me_later_button.clicked.connect(self.close)
        self.download_update_button.clicked.connect(self.download_update)
        
        self.label1.setText(TEXT1)
        self.label2.setText("syRF {} is now available — you have {}. Would you like to download it now?".format(check_update.get_version(), check_update.get_remote_version()))
        self.label3.setText(TEXT3)
        self.textBrowser.setText(NOTES)



    def download_update(self):
        # url = "https://github.com/urbanij/syRF/releases/latest"
        url = "https://github.com/urbanij/syRF"
        try:
            if sys.platform[:3] == "win":
                os.system("start /max {}".format(url))
            else:
                os.system("open {}".format(url))
        except Exception as e:
            print ("Can't open the webpage {}.".format(url))
  

    # A key has been pressed!
    def keyPressEvent(self, event):
        # Did the user press the Escape key?
        if event.key() == QtCore.Qt.Key_Escape or event.key() == QtCore.Qt.Key_W:
            self.close()



if __name__ == "__main__":

    import sys
    app = QtWidgets.QApplication(sys.argv)
    nextGui = mainProgram()
    nextGui.show()
    sys.exit(app.exec_())
