#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Created on Wed Feb 20 17:23:29 CET 2019

@author(s)   : Francesco Urbani
@file        : integrated_matching.py
@descritpion : 

"""

from PyQt5.QtWidgets import QMainWindow, QAction, QStatusBar, QToolBar, QMenuBar, QMessageBox
from PyQt5.QtGui import QIcon
from PyQt5 import QtCore, QtGui, QtWidgets

from new_update_ui import Ui_MainWindow # main ui window autogenerated by PyQt

import sys
import os 
import requests

import check_update



REMOTE_CHANGELOG_URL = 'https://raw.githubusercontent.com/urbanij/syRF/master/.CHANGELOG'

TEXT1 = "<b>A new version  of syRF is available.</b>"
TEXT3 = "<b>Release notes:</b>"

def get_remote_changelog():
    try:
        remote_changelog = requests.get(REMOTE_CHANGELOG_URL).text
        if remote_changelog != '404: Not Found\n':
            return remote_changelog
        else:
            return ""
    except Exception as e:
        print ("Remote file at {} does not exists.".format(REMOTE_CHANGELOG_URL))
        return ""




class mainProgram(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self, parent=None):
        super(mainProgram, self).__init__(parent)
        self.setupUi(self)
        self.setWindowFlags(QtCore.Qt.Window | QtCore.Qt.CustomizeWindowHint | QtCore.Qt.WindowTitleHint | QtCore.Qt.WindowStaysOnTopHint)

        self.remind_me_later_button.clicked.connect(self.close)
        self.download_update_button.clicked.connect(self.download_update)
        
        self.label1.setText(TEXT1)
        self.label2.setText("syRF {} is now available — you have {}. Would you like to download it now?".format(check_update.get_remote_version(), check_update.get_version()))
        self.label3.setText(TEXT3)



        NOTES = "<font><b>Version {}</b><br><br>".format(check_update.get_remote_version())
        NOTES += get_remote_changelog()
        NOTES +="</font>"

        self.textBrowser.setText(NOTES)



    def download_update(self):
        # url = "https://github.com/urbanij/syRF/releases/latest"
        url = "https://github.com/urbanij/syRF"
        try:
            if sys.platform[:3] == "win":
                os.system("start /max {}".format(url))
            else:
                os.system("open {}".format(url))
        except Exception as e:
            print ("Can't open the webpage {}.".format(url))
  



if __name__ == "__main__":

    import sys
    app = QtWidgets.QApplication(sys.argv)
    nextGui = mainProgram()
    nextGui.show()
    sys.exit(app.exec_())
