# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../../../ui/rect2polar.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(377, 230)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setWindowTitle("rect2polar")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.phase_text_browser = QtWidgets.QTextBrowser(self.centralwidget)
        self.phase_text_browser.setMaximumSize(QtCore.QSize(16777215, 21))
        self.phase_text_browser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.phase_text_browser.setObjectName("phase_text_browser")
        self.gridLayout.addWidget(self.phase_text_browser, 4, 1, 1, 1)
        self.P_coord_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.P_coord_lineedit.setObjectName("P_coord_lineedit")
        self.gridLayout.addWidget(self.P_coord_lineedit, 0, 1, 2, 1)
        self.label_82 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_82.sizePolicy().hasHeightForWidth())
        self.label_82.setSizePolicy(sizePolicy)
        self.label_82.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_82.setObjectName("label_82")
        self.gridLayout.addWidget(self.label_82, 0, 0, 2, 1)
        self.mag_text_browser = QtWidgets.QTextBrowser(self.centralwidget)
        self.mag_text_browser.setMaximumSize(QtCore.QSize(16777215, 21))
        self.mag_text_browser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.mag_text_browser.setObjectName("mag_text_browser")
        self.gridLayout.addWidget(self.mag_text_browser, 3, 1, 1, 1)
        self.label_78 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_78.sizePolicy().hasHeightForWidth())
        self.label_78.setSizePolicy(sizePolicy)
        self.label_78.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_78.setObjectName("label_78")
        self.gridLayout.addWidget(self.label_78, 4, 0, 1, 1)
        self.label_83 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_83.sizePolicy().hasHeightForWidth())
        self.label_83.setSizePolicy(sizePolicy)
        self.label_83.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_83.setObjectName("label_83")
        self.gridLayout.addWidget(self.label_83, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.clean_all12_button = QtWidgets.QPushButton(self.centralwidget)
        self.clean_all12_button.setObjectName("clean_all12_button")
        self.horizontalLayout.addWidget(self.clean_all12_button)
        self.calculate12_button = QtWidgets.QPushButton(self.centralwidget)
        self.calculate12_button.setDefault(True)
        self.calculate12_button.setObjectName("calculate12_button")
        self.horizontalLayout.addWidget(self.calculate12_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actiondsd = QtWidgets.QAction(MainWindow)
        self.actiondsd.setObjectName("actiondsd")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.P_coord_lineedit.setPlaceholderText(_translate("MainWindow", "x+jy"))
        self.label_82.setText(_translate("MainWindow", "<html><head/><body><p>P</p></body></html>"))
        self.label_78.setText(_translate("MainWindow", "<html><head/><body><p>phase</p></body></html>"))
        self.label_83.setText(_translate("MainWindow", "<html><head/><body><p>mag</p></body></html>"))
        self.clean_all12_button.setText(_translate("MainWindow", "Clean All"))
        self.calculate12_button.setText(_translate("MainWindow", "Calculate"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actiondsd.setText(_translate("MainWindow", "dsd"))

