#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Created on Mon Mar 19 15:38:35 2018

@author(s)   : Francesco Urbani
@file        : main.py
@descritpion : The main file

"""

from PyQt5.QtWidgets import QMainWindow, QAction, QStatusBar, QToolBar, QMenuBar, QMessageBox
from PyQt5.QtGui import QIcon
from PyQt5 import QtCore, QtGui, QtWidgets
# from PyQt5.QtCore import QSize

from pyui.smith_chart_ui import Ui_MainWindow # main ui window autogenerated by PyQt

import smith_matching
import impedance_at_distance
import gamma2impedance
import lambda4
import stub_matching
import about


msg_error = "" # display nothing if error occurs



class mainProgram(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self, parent=None):
        super(mainProgram, self).__init__(parent)
        self.setupUi(self)

        self.menuBar.setNativeMenuBar(True)
        self.actionImpedance_d.triggered.connect(self.launch_impedance_at_distance)
        self.actionGamma2impedance.triggered.connect(self.launch_gamma2impedance)
        self.action_lambda4.triggered.connect(self.launch_lambda4)
        self.actionStub.triggered.connect(self.launch_stub_matching)
        self.actionAbout_2.triggered.connect(self.open_about_window)




        self.radioButton.setChecked(True) # Z of quarter wave impedance matching set
        


        # MAKE QUARTER WAVE CALCULATE BUTTON AND SHOW SMITH PLOT BUTTON

        # smith_matching

        self.radioButton.toggled['bool'].connect(self.disable_boxes_quarter_wave_im)

        self.Z0_box2.editingFinished.connect(self.Calculate_quarter.click)

        self.Z_in_box.editingFinished.connect(self.Calculate_quarter.click)
        self.Z_out_box.editingFinished.connect(self.Calculate_quarter.click)
        
        self.ZS_box_9.editingFinished.connect(self.Calculate_quarter.click)
        self.ZS_box_6.editingFinished.connect(self.Calculate_quarter.click)
        self.ZS_box_7.editingFinished.connect(self.Calculate_quarter.click)
        self.ZS_box_8.editingFinished.connect(self.Calculate_quarter.click)

        
        self.Calculate_quarter.clicked.connect(self.calculate_tab_quarter_wave_im)
        self.Show_Smith.clicked.connect(self.showSmithPlot)



    def showSmithPlot(self):
        smith_matching.showSmithPlot(self)

    def calculate_tab_quarter_wave_im(self):
        smith_matching.calculate_tab_quarter_wave_im(self)

    def disable_boxes_quarter_wave_im(self):
        smith_matching.disable_boxes_quarter_wave_im(self)

    def launch_impedance_at_distance(self):
        window = impedance_at_distance.mainProgram(self)
        window.show()

    def launch_gamma2impedance(self):
        window = gamma2impedance.mainProgram(self)
        window.show()

    def launch_lambda4(self):
        window = lambda4.mainProgram(self)
        window.show()

    def launch_stub_matching(self):
        window = stub_matching.mainProgram(self)
        window.show()

    

    def open_about_window(self):
        window = about.mainProgram(self)
        window.show()



    # A key has been pressed!
    def keyPressEvent(self, event):
        # Did the user press the Escape key?
        if event.key() == QtCore.Qt.Key_W:
            self.close()




if __name__ == "__main__":

    import sys
    app = QtWidgets.QApplication(sys.argv)
    nextGui = mainProgram()
    nextGui.show()
    sys.exit(app.exec_())
