#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Created on Mon Mar 19 15:38:35 2018

@author(s)   : Francesco Urbani
@file        : main.py
@descritpion : The main file

"""

from PyQt5.QtWidgets import QMainWindow, QAction, QStatusBar, QToolBar, QMenuBar, QMessageBox
from PyQt5.QtGui import QIcon
from PyQt5 import QtCore, QtGui, QtWidgets
# from PyQt5.QtCore import QSize

from smith_chart_ui import Ui_MainWindow # main ui window autogenerated by PyQt

import quarter_wave_matching

msg_error = "" # display nothing if error occurs



class mainProgram(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self, parent=None):
        super(mainProgram, self).__init__(parent)
        self.setupUi(self)


        self.radioButton.setChecked(True) # Z of quarter wave impedance matching set
        


        # MAKE QUARTER WAVE CALCULATE BUTTON AND SHOW SMITH PLOT BUTTON

        # quarter_wave_matching

        self.radioButton.toggled['bool'].connect(self.disable_boxes_quarter_wave_im)

        self.Z0_box2.editingFinished.connect(self.Calculate_quarter.click)

        self.Z_in_box.editingFinished.connect(self.Calculate_quarter.click)
        self.Z_out_box.editingFinished.connect(self.Calculate_quarter.click)
        
        self.ZS_box_9.editingFinished.connect(self.Calculate_quarter.click)
        self.ZS_box_6.editingFinished.connect(self.Calculate_quarter.click)
        self.ZS_box_7.editingFinished.connect(self.Calculate_quarter.click)
        self.ZS_box_8.editingFinished.connect(self.Calculate_quarter.click)

        
        self.Calculate_quarter.clicked.connect(self.calculate_tab_quarter_wave_im)
        self.Show_Smith.clicked.connect(self.showSmithPlot)
        self.clean_all_button213.clicked.connect(self.clean_all_quarter_wave)



    def showSmithPlot(self):
        quarter_wave_matching.showSmithPlot(self)

    def calculate_tab_quarter_wave_im(self):
        quarter_wave_matching.calculate_tab_quarter_wave_im(self)

    def disable_boxes_quarter_wave_im(self):
        quarter_wave_matching.disable_boxes_quarter_wave_im(self)

    def clean_all_quarter_wave(self):
        quarter_wave_matching.clean_all_quarter_wave(self)

    # A key has been pressed!
    def keyPressEvent(self, event):
        # Did the user press the Escape key?
        if event.key() == QtCore.Qt.Key_W:
            self.close()




if __name__ == "__main__":

    import sys
    app = QtWidgets.QApplication(sys.argv)
    nextGui = mainProgram()
    nextGui.show()
    sys.exit(app.exec_())
